import type { SpellingListEntry } from './spellingLists';

export const GRADE_1_CORE_IDS: readonly string[] = [
  'grade-1-cvc-short-vowels-c-k-rule',
  'grade-1-floss-rule',
  'grade-1-consonant-digraphs-final-ck',
  'grade-1-beginning-consonant-blends',
  'grade-1-ending-consonant-blends',
  'grade-1-long-vowels-silent-e',
  'grade-1-open-syllables-final-y',
  'grade-1-heart-words',
  'grade-1-inflectional-endings-s-es',
  'grade-1-inflectional-endings-ed-ing',
  'grade-1-r-controlled-ar-or',
  'grade-1-r-controlled-er-ir-ur',
  'grade-1-long-a-long-o-vowel-teams',
  'grade-1-long-e-vowel-teams',
  'grade-1-tch-dge-ending-rules',
];

export const GRADE_1_GATEWAY_IDS: readonly string[] = [
  'grade-1-short-vowel-practice',
  'grade-1-consonant-digraph-practice',
  'grade-1-beginning-blend-practice',
  'grade-1-ending-blend-practice',
  'grade-1-silent-e-practice',
  'grade-1-heart-word-practice',
  'grade-1-r-controlled-vowel-practice',
  'grade-1-vowel-team-practice',
  'grade-1-tch-dge-practice',
];

export const GRADE_1_TARGETED_SKILL_IDS: readonly string[] = [
  'short-a-words',
  'short-e-words',
  'short-i-words',
  'short-o-words',
  'short-u-words',
  'c-k-ck-words',
  'digraph-sh-words',
  'digraph-ch-words',
  'digraph-th-words',
  'digraph-wh-words',
  'bl-blend-words',
  'br-blend-words',
  'cl-blend-words',
  'cr-blend-words',
  'dr-blend-words',
  'fl-blend-words',
  'fr-blend-words',
  'gl-blend-words',
  'gr-blend-words',
  'pl-blend-words',
  'pr-blend-words',
  'sl-blend-words',
  'sm-blend-words',
  'sn-blend-words',
  'sp-blend-words',
  'st-blend-words',
  'sw-blend-words',
  'tr-blend-words',
  'ld-final-blend-words',
  'nd-final-blend-words',
  'ng-final-blend-words',
  'nk-final-blend-words',
  'nt-final-blend-words',
  'st-final-blend-words',
  'ft-final-blend-words',
  'lk-final-blend-words',
  'lt-final-blend-words',
  'mp-final-blend-words',
  'sk-final-blend-words',
  'silent-e-long-a',
  'silent-e-long-e',
  'silent-e-long-i',
  'silent-e-long-o',
  'silent-e-long-u',
  'grade-1-heart-words-part-1',
  'grade-1-heart-words-part-2',
  'grade-1-heart-words-part-3',
  'r-controlled-ar',
  'r-controlled-or',
  'r-controlled-er-ir-ur',
  'vowel-teams-ai-ay',
  'vowel-teams-oa-ow',
  'vowel-teams-ee-ea',
  'tch-dge-ending-words',
];

export const GRADE_1_VOCABULARY_IDS: readonly string[] = [
  'grade-1-list-01',
  'grade-1-list-02',
  'grade-1-describing-words',
];

export const grade1Badges: Record<string, string> = {
  'grade-1-cvc-short-vowels-c-k-rule': 'Core Unit',
  'grade-1-floss-rule': 'Core Unit',
  'grade-1-consonant-digraphs-final-ck': 'Core Unit',
  'grade-1-beginning-consonant-blends': 'Core Unit',
  'grade-1-ending-consonant-blends': 'Core Unit',
  'grade-1-long-vowels-silent-e': 'Core Unit',
  'grade-1-open-syllables-final-y': 'Core Unit',
  'grade-1-heart-words': 'Core Unit',
  'grade-1-inflectional-endings-s-es': 'Core Unit',
  'grade-1-inflectional-endings-ed-ing': 'Core Unit',
  'grade-1-r-controlled-ar-or': 'Core Unit',
  'grade-1-r-controlled-er-ir-ur': 'Core Unit',
  'grade-1-long-a-long-o-vowel-teams': 'Core Unit',
  'grade-1-long-e-vowel-teams': 'Core Unit',
  'grade-1-tch-dge-ending-rules': 'Core Unit',
  'grade-1-short-vowel-practice': 'Practice Gateway',
  'grade-1-consonant-digraph-practice': 'Practice Gateway',
  'grade-1-beginning-blend-practice': 'Practice Gateway',
  'grade-1-ending-blend-practice': 'Practice Gateway',
  'grade-1-silent-e-practice': 'Practice Gateway',
  'grade-1-heart-word-practice': 'Practice Gateway',
  'grade-1-r-controlled-vowel-practice': 'Practice Gateway',
  'grade-1-vowel-team-practice': 'Practice Gateway',
  'grade-1-tch-dge-practice': 'Practice Gateway',
  'short-a-words': 'Targeted Skill',
  'short-e-words': 'Targeted Skill',
  'short-i-words': 'Targeted Skill',
  'short-o-words': 'Targeted Skill',
  'short-u-words': 'Targeted Skill',
  'c-k-ck-words': 'Targeted Skill',
  'digraph-sh-words': 'Targeted Skill',
  'digraph-ch-words': 'Targeted Skill',
  'digraph-th-words': 'Targeted Skill',
  'digraph-wh-words': 'Targeted Skill',
  'bl-blend-words': 'Targeted Skill',
  'br-blend-words': 'Targeted Skill',
  'cl-blend-words': 'Targeted Skill',
  'cr-blend-words': 'Targeted Skill',
  'dr-blend-words': 'Targeted Skill',
  'fl-blend-words': 'Targeted Skill',
  'fr-blend-words': 'Targeted Skill',
  'gl-blend-words': 'Targeted Skill',
  'gr-blend-words': 'Targeted Skill',
  'pl-blend-words': 'Targeted Skill',
  'pr-blend-words': 'Targeted Skill',
  'sl-blend-words': 'Targeted Skill',
  'sm-blend-words': 'Targeted Skill',
  'sn-blend-words': 'Targeted Skill',
  'sp-blend-words': 'Targeted Skill',
  'st-blend-words': 'Targeted Skill',
  'sw-blend-words': 'Targeted Skill',
  'tr-blend-words': 'Targeted Skill',
  'ld-final-blend-words': 'Targeted Skill',
  'nd-final-blend-words': 'Targeted Skill',
  'ng-final-blend-words': 'Targeted Skill',
  'nk-final-blend-words': 'Targeted Skill',
  'nt-final-blend-words': 'Targeted Skill',
  'st-final-blend-words': 'Targeted Skill',
  'ft-final-blend-words': 'Targeted Skill',
  'lk-final-blend-words': 'Targeted Skill',
  'lt-final-blend-words': 'Targeted Skill',
  'mp-final-blend-words': 'Targeted Skill',
  'sk-final-blend-words': 'Targeted Skill',
  'silent-e-long-a': 'Targeted Skill',
  'silent-e-long-e': 'Targeted Skill',
  'silent-e-long-i': 'Targeted Skill',
  'silent-e-long-o': 'Targeted Skill',
  'silent-e-long-u': 'Targeted Skill',
  'grade-1-heart-words-part-1': 'Targeted Skill',
  'grade-1-heart-words-part-2': 'Targeted Skill',
  'grade-1-heart-words-part-3': 'Targeted Skill',
  'r-controlled-ar': 'Targeted Skill',
  'r-controlled-or': 'Targeted Skill',
  'r-controlled-er-ir-ur': 'Targeted Skill',
  'vowel-teams-ai-ay': 'Targeted Skill',
  'vowel-teams-oa-ow': 'Targeted Skill',
  'vowel-teams-ee-ea': 'Targeted Skill',
  'tch-dge-ending-words': 'Targeted Skill',
  'grade-1-list-01': 'Vocabulary',
  'grade-1-list-02': 'Vocabulary',
  'grade-1-describing-words': 'Vocabulary',
};

export function buildGrade1Sections(allPublishedEntries: SpellingListEntry[]): {
  core: SpellingListEntry[];
  gateways: SpellingListEntry[];
  targeted: SpellingListEntry[];
  vocabulary: SpellingListEntry[];
} {
  const byId = new Map(allPublishedEntries.map((entry) => [entry.data.id, entry]));
  const resolve = (ids: readonly string[]) =>
    ids.map((id) => byId.get(id)).filter((entry): entry is SpellingListEntry => entry !== undefined);

  return {
    core: resolve(GRADE_1_CORE_IDS),
    gateways: resolve(GRADE_1_GATEWAY_IDS),
    targeted: resolve(GRADE_1_TARGETED_SKILL_IDS),
    vocabulary: resolve(GRADE_1_VOCABULARY_IDS),
  };
}
