import type { SpellingWord } from '@/types/spelling';
import { getSentenceBankEntry } from '@/lib/sentenceBank/lookup';
import { shuffleWords } from '@/modules/spellingTest/order';
import type { CuratedSpellingSkillId } from './spellingSkills';

/**
 * A meaning-dependent practice item: `word` cannot be identified from
 * isolated pronunciation alone (a homophone, or another commonly confused
 * spelling), so it carries its own disambiguating sentence. `context` must
 * contain exactly one `___` placeholder standing in for `word`.
 */
export interface SkillPracticeContextItem {
  word: string;
  context: string;
}

/** A bank item is either a plain word (looked up in the shared sentence bank, as before) or a `SkillPracticeContextItem` for meaning-dependent Skills. */
export type SkillPracticeBankItem = string | SkillPracticeContextItem;

/**
 * A Skill practice bank: the canonical, grade-independent pool of practice
 * items for one Skill, distinct from that Skill's (smaller) demonstration
 * set in the Skill's own content frontmatter. See
 * docs/architecture/CONTENT_MODEL.md §3/§4.
 *
 * Most Skills use plain-string items, resolved against the shared sentence
 * bank like any other curated word. Meaning-dependent Skills (Homophones,
 * Commonly Confused Words) use `SkillPracticeContextItem`s instead, so the
 * disambiguating sentence travels with the word rather than being looked up
 * globally by spelling.
 */
export interface SkillPracticeBank {
  skillId: CuratedSpellingSkillId;
  words: SkillPracticeBankItem[];
}

function isContextItem(item: SkillPracticeBankItem): item is SkillPracticeContextItem {
  return typeof item !== 'string';
}

/** The word text of a bank item, regardless of shape — for de-duplication, sorting, etc. */
export function bankItemWord(item: SkillPracticeBankItem): string {
  return isContextItem(item) ? item.word : item;
}

/**
 * Pilot banks only. A Skill with no entry here simply has no practice CTA —
 * that's the whole rollout mechanism for the remaining Skills, not a state
 * that needs to be checked for or handled specially by callers.
 */
export const SKILL_PRACTICE_BANKS: Partial<Record<CuratedSpellingSkillId, SkillPracticeBank>> = {
  'short-a-words': {
    skillId: 'short-a-words',
    words: [
      'cat',
      'hat',
      'mat',
      'sat',
      'pan',
      'can',
      'fan',
      'ran',
      'cap',
      'map',
      'tap',
      'bad',
      'dad',
      'sad',
      'bag',
      'tag',
      'hand',
      'stamp',
    ],
  },
  'digraph-sh-words': {
    skillId: 'digraph-sh-words',
    words: [
      'ship',
      'shop',
      'shut',
      'shin',
      'shell',
      'wish',
      'brush',
      'dish',
      'fish',
      'wash',
      'mush',
      'fishing',
      'washing',
    ],
  },
  'silent-e-long-a': {
    skillId: 'silent-e-long-a',
    words: [
      'cake',
      'bake',
      'lake',
      'make',
      'take',
      'wake',
      'gate',
      'late',
      'date',
      'plate',
      'skate',
      'flame',
      'game',
      'name',
      'same',
      'tame',
      'cape',
      'grape',
      'shape',
      'tape',
      'brave',
      'cave',
      'gave',
      'save',
      'wave',
    ],
  },
  'ck-tch-dge-word-endings': {
    skillId: 'ck-tch-dge-word-endings',
    words: [
      'back',
      'duck',
      'rock',
      'pick',
      'staff',
      'bell',
      'moss',
      'cliff',
      'buzz',
      'fuzz',
      'jazz',
      'catch',
      'pitch',
      'notch',
      'hutch',
      'badge',
      'bridge',
      'lodge',
      'fudge',
    ],
  },
  'common-suffixes': {
    skillId: 'common-suffixes',
    words: [
      'helpful',
      'hopeful',
      'careful',
      'thoughtful',
      'careless',
      'hopeless',
      'kindness',
      'darkness',
      'enjoyment',
      'movement',
      'faster',
      'fastest',
      'slower',
      'slowest',
      'smaller',
      'smallest',
    ],
  },
  'multisyllabic-words': {
    skillId: 'multisyllabic-words',
    words: [
      'rabbit',
      'basket',
      'kitten',
      'chicken',
      'pencil',
      'garden',
      'robot',
      'paper',
      'music',
      'baby',
      'table',
      'little',
      'apple',
      'simple',
      'gentle',
      'circle',
      'turtle',
      'sunset',
      'winter',
      'number',
    ],
  },
  'short-e-words': {
    skillId: 'short-e-words',
    words: [
      'bed',
      'fed',
      'led',
      'red',
      'wed',
      'hen',
      'ten',
      'men',
      'pen',
      'den',
      'bet',
      'get',
      'net',
      'pet',
      'leg',
      'beg',
      'peg',
      'tent',
      'step',
      'nest',
    ],
  },
  'short-i-words': {
    skillId: 'short-i-words',
    words: [
      'bit',
      'fit',
      'hit',
      'kit',
      'sit',
      'big',
      'dig',
      'fig',
      'pig',
      'wig',
      'bin',
      'fin',
      'pin',
      'tin',
      'win',
      'dip',
      'hip',
      'lip',
      'rip',
      'tip',
      'dish',
      'fish',
      'wish',
      'hill',
    ],
  },
  'short-o-words': {
    skillId: 'short-o-words',
    words: [
      'cot',
      'dot',
      'got',
      'hot',
      'not',
      'pot',
      'hop',
      'mop',
      'pop',
      'top',
      'dog',
      'fog',
      'jog',
      'log',
      'dock',
      'lock',
      'rock',
      'sock',
      'pond',
      'moth',
    ],
  },
  'short-u-words': {
    skillId: 'short-u-words',
    words: [
      'bug',
      'hug',
      'jug',
      'mug',
      'rug',
      'bun',
      'fun',
      'run',
      'sun',
      'cub',
      'rub',
      'tub',
      'dust',
      'just',
      'must',
      'trust',
      'cup',
      'drum',
    ],
  },
  'digraph-ch-words': {
    skillId: 'digraph-ch-words',
    words: ['chin', 'chip', 'chop', 'chest', 'lunch', 'much', 'rich', 'such'],
  },
  'digraph-th-words': {
    skillId: 'digraph-th-words',
    words: ['that', 'this', 'them', 'think', 'math', 'bath', 'path'],
  },
  'digraph-wh-words': {
    skillId: 'digraph-wh-words',
    words: [
      'what',
      'when',
      'where',
      'whip',
      'while',
      'why',
      'wheel',
      'white',
      'who',
      'whom',
      'whose',
      'whole',
    ],
  },
  'silent-e-long-i': {
    skillId: 'silent-e-long-i',
    words: [
      'bike',
      'hike',
      'like',
      'spike',
      'fine',
      'line',
      'mine',
      'nine',
      'pine',
      'shine',
      'hide',
      'ride',
      'side',
      'slide',
      'wide',
      'chime',
      'dime',
      'lime',
      'time',
    ],
  },
  'silent-e-long-o': {
    skillId: 'silent-e-long-o',
    words: [
      'home',
      'hope',
      'note',
      'stone',
      'chose',
      'bone',
      'cone',
      'rope',
      'slope',
      'vote',
      'broke',
      'joke',
      'poke',
      'smoke',
    ],
  },
  'silent-e-long-u': {
    skillId: 'silent-e-long-u',
    words: ['cube', 'cute', 'huge', 'mule', 'fuse', 'rule', 'flute', 'prune', 'tune', 'tube'],
  },
  'r-controlled-ar': {
    skillId: 'r-controlled-ar',
    words: [
      'art',
      'car',
      'dark',
      'farm',
      'hard',
      'park',
      'sharp',
      'yard',
      'far',
      'star',
      'cart',
      'start',
      'shark',
      'arm',
    ],
  },
  'r-controlled-or': {
    skillId: 'r-controlled-or',
    words: [
      'corn',
      'for',
      'form',
      'horse',
      'morning',
      'north',
      'short',
      'story',
      'born',
      'torn',
      'sort',
      'storm',
      'glory',
      'worn',
    ],
  },
  'r-controlled-er-ir-ur': {
    skillId: 'r-controlled-er-ir-ur',
    words: [
      'her',
      'fern',
      'term',
      'bird',
      'first',
      'girl',
      'turn',
      'hurt',
      'turtle',
      'sister',
      'winter',
      'under',
    ],
  },
  'vowel-teams-ai-ay': {
    skillId: 'vowel-teams-ai-ay',
    words: [
      'chain',
      'mail',
      'nail',
      'paint',
      'rain',
      'snail',
      'train',
      'wait',
      'day',
      'play',
      'stay',
      'way',
    ],
  },
  'vowel-teams-ee-ea': {
    skillId: 'vowel-teams-ee-ea',
    words: [
      'bee',
      'feel',
      'feet',
      'free',
      'keep',
      'need',
      'sleep',
      'tree',
      'week',
      'beach',
      'clean',
      'dream',
      'eat',
      'heat',
      'speak',
      'team',
    ],
  },
  'vowel-teams-oa-ow': {
    skillId: 'vowel-teams-oa-ow',
    words: ['boat', 'coat', 'goat', 'road', 'soap', 'blow', 'crow', 'flow', 'grow', 'know', 'snow'],
  },
  'oi-and-oy-words': {
    skillId: 'oi-and-oy-words',
    words: [
      'oil',
      'coin',
      'point',
      'voice',
      'noise',
      'soil',
      'boy',
      'joy',
      'enjoy',
      'royal',
      'loyal',
      'toy',
    ],
  },
  'ou-and-ow-words': {
    skillId: 'ou-and-ow-words',
    words: [
      'out',
      'loud',
      'found',
      'round',
      'sound',
      'ground',
      'mouse',
      'mouth',
      'cow',
      'brown',
      'down',
      'now',
      'town',
      'clown',
      'crown',
      'howl',
    ],
  },
  'ie-and-igh-words': {
    skillId: 'ie-and-igh-words',
    words: [
      'pie',
      'tie',
      'lie',
      'die',
      'high',
      'sigh',
      'night',
      'light',
      'right',
      'might',
      'sight',
      'bright',
      'flight',
    ],
  },
  'oo-words': {
    skillId: 'oo-words',
    words: [
      'moon',
      'food',
      'zoo',
      'spoon',
      'soon',
      'room',
      'smooth',
      'book',
      'look',
      'foot',
      'good',
      'took',
      'wood',
      'hood',
    ],
  },
  'au-and-aw-words': {
    skillId: 'au-and-aw-words',
    words: [
      'saw',
      'draw',
      'lawn',
      'crawl',
      'hawk',
      'cause',
      'author',
      'haul',
      'because',
      'fault',
      'vault',
    ],
  },
  'beginning-blends': {
    skillId: 'beginning-blends',
    words: [
      'black',
      'blob',
      'clap',
      'clip',
      'flag',
      'flat',
      'glad',
      'glow',
      'plum',
      'plan',
      'slip',
      'sled',
      'brag',
      'bring',
      'crab',
      'cry',
      'drum',
      'drip',
      'frog',
      'free',
      'grab',
      'green',
      'prize',
      'print',
      'train',
      'trip',
      'smile',
      'small',
      'snack',
      'snap',
      'spin',
      'spot',
      'stop',
      'star',
      'swim',
      'swing',
      'scrub',
      'sprint',
      'strap',
      'splat',
    ],
  },
  'ending-blends': {
    skillId: 'ending-blends',
    words: [
      'jump',
      'lamp',
      'camp',
      'hand',
      'sand',
      'land',
      'sink',
      'pink',
      'junk',
      'tent',
      'hunt',
      'mint',
      'gift',
      'lift',
      'raft',
      'milk',
      'silk',
      'elk',
      'belt',
      'melt',
      'salt',
      'desk',
      'mask',
      'task',
      'cold',
      'gold',
      'help',
      'yelp',
    ],
  },
  'silent-letters': {
    skillId: 'silent-letters',
    words: [
      'write',
      'wrap',
      'wrist',
      'wrote',
      'wrong',
      'wreck',
      'know',
      'knee',
      'knot',
      'knew',
      'knock',
      'knife',
      'thumb',
      'lamb',
      'crumb',
      'comb',
      'climb',
      'numb',
    ],
  },
  'soft-c-soft-g': {
    skillId: 'soft-c-soft-g',
    words: [
      'city',
      'ice',
      'icy',
      'circus',
      'place',
      'face',
      'race',
      'nice',
      'giant',
      'page',
      'gym',
      'cage',
      'large',
      'change',
    ],
  },
  plurals: {
    skillId: 'plurals',
    words: [
      'cats',
      'dogs',
      'cups',
      'beds',
      'books',
      'trees',
      'buses',
      'boxes',
      'dishes',
      'wishes',
      'brushes',
      'fixes',
      'buzzes',
      'passes',
      'lunches',
      'foxes',
    ],
  },
  'ed-and-ing': {
    skillId: 'ed-and-ing',
    words: [
      'jumped',
      'jumping',
      'helped',
      'helping',
      'played',
      'playing',
      'rested',
      'resting',
      'looked',
      'looking',
      'called',
      'calling',
    ],
  },
  'suffix-spelling-changes': {
    skillId: 'suffix-spelling-changes',
    words: [
      'running',
      'stopped',
      'bigger',
      'sitting',
      'planned',
      'making',
      'hoped',
      'safer',
      'smiled',
      'carried',
      'cried',
      'happier',
      'funniest',
      'happiness',
      'cities',
      'hopeful',
      'careless',
      'carrying',
    ],
  },
  'compound-words': {
    skillId: 'compound-words',
    words: [
      'sunshine',
      'backpack',
      'notebook',
      'snowman',
      'sunset',
      'toothbrush',
      'rainbow',
      'weekend',
      'bedroom',
      'football',
      'birthday',
      'cupcake',
    ],
  },
  contractions: {
    skillId: 'contractions',
    words: [
      "can't",
      "don't",
      "didn't",
      "isn't",
      "wasn't",
      "won't",
      "I'm",
      "she's",
      "we're",
      "they're",
      "he's",
      "it's",
      "that's",
      "I'll",
      "she'll",
      "they'll",
    ],
  },
  'un-and-re-prefixes': {
    skillId: 'un-and-re-prefixes',
    words: [
      'unfair',
      'unhappy',
      'unkind',
      'unsafe',
      'unlock',
      'redo',
      'replay',
      'reread',
      'rewrite',
      'retell',
    ],
  },
  'common-prefixes': {
    skillId: 'common-prefixes',
    words: [
      'disagree',
      'dislike',
      'discover',
      'dishonest',
      'misread',
      'misplace',
      'misspell',
      'predict',
      'preview',
      'interact',
      'interfere',
      'intermission',
      'international',
      'submarine',
      'subway',
      'substitute',
      'superstar',
      'supervise',
      'transport',
      'transplant',
      'transform',
      'transfer',
      'antifreeze',
      'antibiotic',
    ],
  },
  'greek-and-latin-roots': {
    skillId: 'greek-and-latin-roots',
    words: [
      'transport',
      'portable',
      'transportation',
      'predict',
      'dictate',
      'prediction',
      'inspect',
      'spectator',
      'inspection',
      'telephone',
      'telescope',
      'microscope',
      'biography',
      'national',
      'critical',
    ],
  },
  homophones: {
    skillId: 'homophones',
    words: [
      { word: 'to', context: 'Please walk ___ the door and knock.' },
      { word: 'too', context: 'The soup was ___ hot to eat right away.' },
      { word: 'two', context: 'I have ___ dogs at home.' },
      { word: 'there', context: 'Put the backpack right ___ by the door.' },
      { word: 'their', context: 'The students put ___ books on the table.' },
      { word: "they're", context: '___ coming to the party after school.' },
    ],
  },
  'commonly-confused-words': {
    skillId: 'commonly-confused-words',
    words: [
      { word: 'affect', context: 'Loud noise can ___ how well you sleep.' },
      { word: 'effect', context: 'Getting more sleep had a good ___ on his grades.' },
      { word: 'principal', context: 'The school ___ greeted the class this morning.' },
      { word: 'principle', context: 'Honesty is an important ___ to live by.' },
      { word: 'advice', context: 'She gave her friend some helpful ___ about the test.' },
      { word: 'advise', context: 'The coach will ___ the team before the big game.' },
      { word: 'than', context: 'This book is longer ___ that one.' },
      { word: 'then', context: 'We ate lunch, and ___ we went outside to play.' },
    ],
  },
};

/** Looks up a Skill's practice bank, or `undefined` if it doesn't have one yet. */
export function getSkillPracticeBank(skillId: string): SkillPracticeBank | undefined {
  return SKILL_PRACTICE_BANKS[skillId as CuratedSpellingSkillId];
}

/**
 * Maps a bank's items to playable `SpellingWord`s. Plain-string items are
 * resolved against the shared sentence bank, mirroring `spellingLists.ts`'s
 * `toPlayableWords`. `SkillPracticeContextItem`s fill their own `context`
 * template into `exampleSentence` (for speech) and keep the blanked
 * template as `contextSentence` (for on-screen display), flagged
 * `contextRequired` so `/play` knows to present context before the word.
 */
export function toPlayableSkillPracticeWords(bank: SkillPracticeBank): SpellingWord[] {
  return bank.words.map((item) => {
    if (isContextItem(item)) {
      return {
        word: item.word,
        exampleSentence: item.context.replace('___', item.word),
        contextSentence: item.context,
        contextRequired: true,
      };
    }
    return {
      word: item,
      exampleSentence: getSentenceBankEntry(item)?.exampleSentence,
    };
  });
}

/**
 * Selects a bounded, shuffled practice session from a Skill's bank. Default
 * session size of 10 matches the curated-collection default already decided
 * in docs/LEARNING_MODEL.md; a bank smaller than that simply yields the
 * whole (shuffled) bank.
 */
export function selectSkillPracticeSession<T>(
  words: readonly T[],
  sessionSize = 10,
  rng: () => number = Math.random,
): T[] {
  return shuffleWords(words, rng).slice(0, sessionSize);
}
