import type { SentenceBankEntry } from './types';

export const SENTENCE_BANK: SentenceBankEntry[] = [
  // K-1
  { word: 'cat', exampleSentence: 'The cat sat on the soft rug.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'dog', exampleSentence: 'My dog loves to play in the yard.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'big', exampleSentence: 'The big elephant splashed in the water.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'run', exampleSentence: 'We run to the park after school.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'jump', exampleSentence: 'She can jump over the puddle.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'day', exampleSentence: 'It was a sunny day at the beach.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'night', exampleSentence: 'Stars shine in the sky at night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'rain', exampleSentence: 'The rain made puddles on the sidewalk.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'snow', exampleSentence: 'We built a snowman in the fluffy snow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hand', exampleSentence: 'She raised her hand to answer the question.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'girl', exampleSentence: 'The girl read a book under the tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fish', exampleSentence: 'We saw a colorful fish in the pond.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bird', exampleSentence: 'A little bird sang outside the window.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'tree', exampleSentence: 'An apple grows on that tall tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'help', exampleSentence: 'Can you help me carry these books?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'like', exampleSentence: 'I like to read before bedtime.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'love', exampleSentence: 'We love spending time with our family.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'want', exampleSentence: 'Do you want a glass of water?', gradeBand: 'K-1', sourceType: 'curated' },
  // K-1 — Reading Rockets Basic Spelling Vocabulary List, Grade 1
  { word: 'a', exampleSentence: 'I see a big red ball.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'all', exampleSentence: 'We eat all of the grapes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'am', exampleSentence: 'I am six years old.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'and', exampleSentence: 'I have a cat and a dog.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'at', exampleSentence: 'We are at the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ball', exampleSentence: 'The red ball rolls down the hill.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'be', exampleSentence: 'I want to be a teacher.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bed', exampleSentence: 'I sleep in my warm bed.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'box', exampleSentence: 'The toys are in the box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'boy', exampleSentence: 'The boy kicks the ball.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'but', exampleSentence: 'I want to play, but it is raining.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'came', exampleSentence: 'My friend came over to play.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'can', exampleSentence: 'We put the soup in a can.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'car', exampleSentence: 'Dad drives the car to the store.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'come', exampleSentence: 'Please come and sit with me.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'cow', exampleSentence: 'The cow eats grass in the field.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'dad', exampleSentence: 'My dad reads me a story.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'did', exampleSentence: 'I did my homework after lunch.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'do', exampleSentence: 'I do my chores every day.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fat', exampleSentence: 'The fat pig rolls in the mud.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'for', exampleSentence: 'This gift is for you.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fun', exampleSentence: 'We have fun at the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'get', exampleSentence: 'I get a glass of water.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'go', exampleSentence: 'We go to school on the bus.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'good', exampleSentence: 'She is a good friend.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'got', exampleSentence: 'I got a new toy today.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'had', exampleSentence: 'We had soup for lunch.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hat', exampleSentence: 'I wear a warm hat in the snow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'he', exampleSentence: 'He runs to the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hen', exampleSentence: 'The hen sits on her eggs.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'here', exampleSentence: 'Come and sit here with me.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'him', exampleSentence: 'I give the ball to him.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'his', exampleSentence: 'He puts on his shoes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'home', exampleSentence: 'We walk home after school.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hot', exampleSentence: 'The soup is too hot to eat.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'I', exampleSentence: 'I like to ride my bike.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'if', exampleSentence: 'We can play if it stops raining.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'in', exampleSentence: 'The cat sleeps in the box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'into', exampleSentence: 'The dog jumps into the water.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'is', exampleSentence: 'The sky is blue today.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'it', exampleSentence: 'I see a ball and kick it.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'its', exampleSentence: 'The dog wags its tail.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'let', exampleSentence: 'Let me help you carry that.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'look', exampleSentence: 'Look at the bird in the tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'man', exampleSentence: 'The man waters his garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'me', exampleSentence: 'Can you give the book to me?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'mom', exampleSentence: 'My mom makes pancakes for breakfast.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'my', exampleSentence: 'My shoes are by the door.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'no', exampleSentence: 'There are no clouds in the sky.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'not', exampleSentence: 'The water is not cold.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'of', exampleSentence: 'I drink a glass of milk.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'old', exampleSentence: 'My shoes are old and worn.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'on', exampleSentence: 'The cat sits on the rug.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'one', exampleSentence: 'I have one apple in my bag.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'out', exampleSentence: 'We go out to play in the yard.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'pan', exampleSentence: 'Mom cooks eggs in the pan.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'pet', exampleSentence: 'My pet cat likes to nap.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'pig', exampleSentence: 'The little pig eats from a bowl.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ran', exampleSentence: 'We ran around the playground.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'rat', exampleSentence: 'A small rat hides under the box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'red', exampleSentence: 'I have a red wagon.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ride', exampleSentence: 'I ride my bike to the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sat', exampleSentence: 'We sat under the big tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'see', exampleSentence: 'I can see the moon at night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'she', exampleSentence: 'She paints a picture of a cat.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sit', exampleSentence: 'Please sit in your chair.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'six', exampleSentence: 'I have six crayons in my box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'so', exampleSentence: 'The sun is so bright today.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'stop', exampleSentence: 'We stop at the red light.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sun', exampleSentence: 'The sun is warm on my face.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ten', exampleSentence: 'I can count to ten.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'the', exampleSentence: 'The dog runs in the yard.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'this', exampleSentence: 'This apple tastes sweet.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'to', exampleSentence: 'We walk to the park together.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'top', exampleSentence: 'The spinning top falls on its side.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'toy', exampleSentence: 'My favorite toy is a soft bear.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'two', exampleSentence: 'I have two red apples.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'up', exampleSentence: 'The balloon floats up into the sky.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'us', exampleSentence: 'Mom reads a story to us.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'was', exampleSentence: 'The sky was clear last night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'we', exampleSentence: 'We play in the park together.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'yes', exampleSentence: 'Yes, I would like some water.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'you', exampleSentence: 'Can you help me find my shoes?', gradeBand: 'K-1', sourceType: 'curated' },
  // 2-3
  { word: 'play', exampleSentence: 'The children play outside after lunch.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'book', exampleSentence: 'She borrowed a book from the library.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'water', exampleSentence: 'Remember to drink plenty of water each day.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'small', exampleSentence: 'A small kitten hid under the chair.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'cold', exampleSentence: 'Put on your coat because it is cold outside.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'fast', exampleSentence: 'The fast rabbit reached the finish line first.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'slow', exampleSentence: 'The slow turtle finished the race last.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'flower', exampleSentence: 'She planted a flower in the garden.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'happy', exampleSentence: 'Everyone felt happy on the last day of school.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'learn', exampleSentence: 'We learn something new every day.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'write', exampleSentence: 'Please write your name at the top of the page.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'mother', exampleSentence: 'My mother makes the best soup.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'father', exampleSentence: 'Her father teaches at the school nearby.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'about', exampleSentence: 'We read a book about frogs and ponds.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'add', exampleSentence: 'I can add two and three to get five.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'after', exampleSentence: 'We went for a walk after dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ago', exampleSentence: 'We visited the farm a long time ago.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'an', exampleSentence: 'She found an acorn under the oak tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'any', exampleSentence: 'Do you have any apples left?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'apple', exampleSentence: 'She packed an apple in her lunch box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'are', exampleSentence: 'The ducks are swimming in the pond.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'as', exampleSentence: 'The puppy is as soft as a pillow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ask', exampleSentence: 'You can ask me if you need help.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ate', exampleSentence: 'We ate soup and bread for dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'away', exampleSentence: 'The butterfly flew away into the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'baby', exampleSentence: 'The baby laughed and clapped her hands.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'back', exampleSentence: 'Put the book back on the shelf.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bad', exampleSentence: 'The bad weather kept us inside all day.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bag', exampleSentence: 'She packed her bag for the trip to school.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'base', exampleSentence: 'The lamp sits on a round wooden base.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'bat', exampleSentence: 'He picked up the bat and got ready to swing.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bee', exampleSentence: 'A yellow bee landed on the flower.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'been', exampleSentence: 'Have you ever been to a farm before?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'before', exampleSentence: 'Brush your teeth before you go to sleep.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'being', exampleSentence: 'She is being very kind to her little brother.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'best', exampleSentence: 'My dog is my very best friend.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bike', exampleSentence: 'She rode her bike down the winding path.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bill', exampleSentence: 'The duck had a wide orange bill.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'black', exampleSentence: 'The black cat sat on the warm porch.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'blue', exampleSentence: 'The sky was clear and bright blue.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'boat', exampleSentence: 'We watched a little boat sail on the lake.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'both', exampleSentence: 'Both puppies wanted to play with the ball.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bring', exampleSentence: 'Please bring your raincoat to school today.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'brother', exampleSentence: 'My brother and I play in the yard together.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'brown', exampleSentence: 'A brown rabbit hopped into the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bus', exampleSentence: 'We ride the bus to school every morning.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'buy', exampleSentence: 'We stop at the store to buy fresh bread.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'by', exampleSentence: 'The dog slept by the warm fireplace.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'cake', exampleSentence: 'She blew out the candles on her birthday cake.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'call', exampleSentence: 'I will call you when I get home.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'candy', exampleSentence: 'She saved one piece of candy for later.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'change', exampleSentence: 'The leaves change color in the fall.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'child', exampleSentence: 'Every child in the class got a new book.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'city', exampleSentence: 'We drove through the busy city on our trip.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'clean', exampleSentence: 'Please clean up your toys before dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'club', exampleSentence: 'She joined the art club at school.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'coat', exampleSentence: 'Button up your coat before going outside.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'coming', exampleSentence: 'The train is coming around the bend.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'corn', exampleSentence: 'We picked fresh corn from the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'could', exampleSentence: 'She could hear the birds singing outside.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'cry', exampleSentence: 'The baby would cry when she was hungry.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'cup', exampleSentence: 'He poured milk into a blue cup.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'cut', exampleSentence: 'She cut the paper into small stars.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'daddy', exampleSentence: 'Daddy reads me a story every night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'dear', exampleSentence: 'She wrote to her dear grandmother every month.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'deep', exampleSentence: 'The well is very deep and full of cool water.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'deer', exampleSentence: 'A deer stood quietly in the tall grass.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'doing', exampleSentence: 'What are you doing with all those crayons?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'doll', exampleSentence: 'She tucked her doll into a little blanket.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'door', exampleSentence: 'Please close the door so the cat stays inside.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'down', exampleSentence: 'The leaf floated slowly down from the branch.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'dress', exampleSentence: 'She wore a yellow dress to the picnic.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'drive', exampleSentence: 'We drive past the farm on the way to town.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'drop', exampleSentence: 'Be careful not to drop the eggs.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'dry', exampleSentence: 'She used a towel to dry her hands.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'duck', exampleSentence: 'A fluffy duck waddled to the edge of the pond.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'each', exampleSentence: 'Each child got a turn to read aloud.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'eat', exampleSentence: 'We eat together as a family every evening.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'eating', exampleSentence: 'The rabbit was eating a carrot in the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'egg', exampleSentence: 'She cracked an egg into the mixing bowl.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'end', exampleSentence: 'We sat at the end of the long table.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fall', exampleSentence: 'Red and yellow leaves fall from the trees.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'far', exampleSentence: 'The mountains look small because they are so far away.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'farm', exampleSentence: 'We visited a farm and saw pigs and cows.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'feed', exampleSentence: 'We feed the ducks bread at the pond.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'feel', exampleSentence: 'The soft blanket makes me feel cozy.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'feet', exampleSentence: 'Mud squished between her toes and under her feet.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fell', exampleSentence: 'A ripe apple fell from the tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'find', exampleSentence: 'Can you find the hidden star in the picture?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fine', exampleSentence: 'The weather was fine for a walk in the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fire', exampleSentence: 'The fireplace kept the whole room warm.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'first', exampleSentence: 'She was the first to finish her drawing.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'five', exampleSentence: 'I counted five ducks on the pond.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fix', exampleSentence: 'Dad helped me fix the broken wheel on my toy.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'flag', exampleSentence: 'The flag waved in the gentle breeze.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'floor', exampleSentence: 'The cat curled up on the warm floor.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fly', exampleSentence: 'We watched a butterfly fly from flower to flower.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'food', exampleSentence: 'We packed food for our picnic in the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'foot', exampleSentence: 'She put on one sock on each foot.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'four', exampleSentence: 'The puppy had four tiny white paws.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fox', exampleSentence: 'A red fox peeked out from behind the bushes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'from', exampleSentence: 'We got a postcard from our grandparents.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'full', exampleSentence: 'My backpack is full of books and crayons.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'funny', exampleSentence: 'The clown made a funny face to make us laugh.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'game', exampleSentence: 'We played a card game after dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'gas', exampleSentence: 'Dad stopped to put gas in the car.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'gave', exampleSentence: 'Grandma gave us a warm hug hello.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'give', exampleSentence: 'She wanted to give her friend a card.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'glad', exampleSentence: 'I am glad you came to visit us.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'goat', exampleSentence: 'A friendly goat ate grass near the fence.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'goes', exampleSentence: 'The sun goes down behind the hills each evening.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'going', exampleSentence: 'We are going to the library after lunch.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'gold', exampleSentence: 'The autumn leaves turned orange and gold.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'gone', exampleSentence: 'By morning the snow was already gone.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'grade', exampleSentence: 'She moved up to the next grade at school.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'grass', exampleSentence: 'We lay on the soft grass and looked at clouds.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'green', exampleSentence: 'The frogs sat on the green lily pads.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'grow', exampleSentence: 'We planted seeds and watched them grow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hard', exampleSentence: 'The frozen ground was hard under our boots.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'has', exampleSentence: 'My dog has soft brown ears.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'have', exampleSentence: 'We have a garden full of tomatoes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hear', exampleSentence: 'I can hear the birds singing in the morning.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hill', exampleSentence: 'We rolled down the grassy hill together.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hit', exampleSentence: 'She hit the ball with the wooden bat.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hold', exampleSentence: 'Please hold my hand when we cross the street.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hole', exampleSentence: 'A small rabbit looked out from its hole.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hop', exampleSentence: 'The bunny likes to hop around the yard.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hope', exampleSentence: 'I hope the sun comes out tomorrow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'horse', exampleSentence: 'The horse trotted slowly around the field.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'how', exampleSentence: 'She showed me how to tie my shoes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ice', exampleSentence: 'We saw ducks walking on the thin ice.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'inch', exampleSentence: 'The tiny worm was less than one inch long.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'inside', exampleSentence: 'We came inside when it started to rain.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'job', exampleSentence: 'Everyone had a job to do to set the table.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'just', exampleSentence: 'I just finished reading my favorite book.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'keep', exampleSentence: 'Please keep your room clean and tidy.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'king', exampleSentence: 'The story was about a kind and gentle king.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'know', exampleSentence: 'I know all the words to that song.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'lake', exampleSentence: 'We paddled a canoe across the quiet lake.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'land', exampleSentence: 'We watched the plane land gently on the runway.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'last', exampleSentence: 'She saved the last cookie for her brother.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'late', exampleSentence: 'The bus was late because of the heavy rain.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'lay', exampleSentence: 'The cat likes to lay in the patch of sunlight.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'left', exampleSentence: 'Turn left at the corner to find the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'leg', exampleSentence: 'The grasshopper jumped with its long back leg.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'light', exampleSentence: 'The morning light came softly through the curtain.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'line', exampleSentence: 'We stood in a line to get our books.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'little', exampleSentence: 'A little mouse peeked out from behind the wall.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'live', exampleSentence: 'We live close to the park and the library.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'lives', exampleSentence: 'The friendly cat lives next door to us.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'long', exampleSentence: 'The path through the woods was long and winding.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'looking', exampleSentence: 'She was looking for her lost mitten.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'lost', exampleSentence: 'He found his lost toy under the bed.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'lot', exampleSentence: 'We had a lot of fun at the fair.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'mad', exampleSentence: 'He was a little mad but calmed down quickly.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'made', exampleSentence: 'She made a card for her grandmother.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'make', exampleSentence: 'Let us make a birdhouse out of wood.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'many', exampleSentence: 'There were many stars in the clear night sky.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'meat', exampleSentence: 'We had soup with vegetables and a little meat.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'men', exampleSentence: 'The men worked together to build the garden fence.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'met', exampleSentence: 'She met her new friend at the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'mile', exampleSentence: 'The farm is about a mile down the road.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'milk', exampleSentence: 'She poured a tall glass of cold milk.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'mine', exampleSentence: 'That red crayon is mine.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'miss', exampleSentence: 'I miss my grandpa when he travels far away.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'moon', exampleSentence: 'The moon was round and bright last night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'more', exampleSentence: 'May I have a little more soup, please?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'most', exampleSentence: 'Most of the apples were ripe and ready.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'move', exampleSentence: 'We had to move the table to make room.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'much', exampleSentence: 'Thank you so much for helping me.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'must', exampleSentence: 'You must wash your hands before eating.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'myself', exampleSentence: 'I made the card all by myself.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'nail', exampleSentence: 'Dad used a hammer and nail to hang the picture.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'name', exampleSentence: 'Write your name at the top of the page.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'need', exampleSentence: 'We need to pack our bags before the trip.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'new', exampleSentence: 'She got a new book from the library.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'next', exampleSentence: 'We will bake cookies next weekend.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'nice', exampleSentence: 'It was nice to see everyone at the gathering.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'nine', exampleSentence: 'There were nine ducklings following the mother duck.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'north', exampleSentence: 'We drove north to see the mountains.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'now', exampleSentence: 'It is time to go inside now.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'nut', exampleSentence: 'The squirrel found a nut and carried it home.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'off', exampleSentence: 'She turned off the light and went to sleep.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'only', exampleSentence: 'There was only one slice of pie left.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'open', exampleSentence: 'She pulled the door open with both hands.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'or', exampleSentence: 'Would you like milk or water with dinner?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'other', exampleSentence: 'The other children waited at the gate.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'our', exampleSentence: 'We planted flowers in our garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'outside', exampleSentence: 'Let us go outside and play in the leaves.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'over', exampleSentence: 'The cat jumped over the garden wall.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'page', exampleSentence: 'She turned the page and kept reading.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'park', exampleSentence: 'We had a picnic at the park on Sunday.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'part', exampleSentence: 'We each did our part to clean up.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'pay', exampleSentence: 'Mom let me pay for the apples at the market.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'pick', exampleSentence: 'We went to pick strawberries at the farm.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'plant', exampleSentence: 'She helped plant seeds in the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'playing', exampleSentence: 'The children were playing in the fallen leaves.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'pony', exampleSentence: 'She gently brushed the pony\'s soft mane.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'post', exampleSentence: 'He put the letter in the post box.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'pull', exampleSentence: 'She had to pull hard to open the drawer.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'put', exampleSentence: 'Please put your shoes by the door.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'rabbit', exampleSentence: 'A white rabbit nibbled on the clover.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'read', exampleSentence: 'Dad read us a chapter every night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'rest', exampleSentence: 'The puppy curled up for a rest in the sunshine.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'riding', exampleSentence: 'She waved as she was riding past on her bike.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'road', exampleSentence: 'We walked along the quiet country road.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'rock', exampleSentence: 'She found a smooth shiny rock by the stream.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'room', exampleSentence: 'Her room was cozy with soft rugs and pillows.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'said', exampleSentence: 'She said hello to every neighbor on the street.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'same', exampleSentence: 'We wore the same color shirt to the picnic.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sang', exampleSentence: 'The birds sang sweetly in the morning.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'saw', exampleSentence: 'I saw a rainbow after the rain.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'say', exampleSentence: 'What did she say when she opened the gift?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sea', exampleSentence: 'We collected shells at the edge of the sea.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'seat', exampleSentence: 'She found a cozy seat by the window.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'seem', exampleSentence: 'The kittens seem happy in their new home.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'seen', exampleSentence: 'I have never seen so many fireflies at once.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'send', exampleSentence: 'Let us send a card to our grandparents.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'set', exampleSentence: 'We set the table before everyone arrived.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'seven', exampleSentence: 'She counted seven eggs in the nest.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sheep', exampleSentence: 'The fluffy sheep grazed in the meadow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ship', exampleSentence: 'We watched the big ship sail out to sea.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'shoe', exampleSentence: 'She tied the bow on her shoe.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'show', exampleSentence: 'Let me show you how to fold a paper crane.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sick', exampleSentence: 'He stayed home with warm soup when he felt sick.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'side', exampleSentence: 'She planted flowers on each side of the path.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sing', exampleSentence: 'We love to sing songs on long car rides.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sky', exampleSentence: 'The sky turned pink and orange at sunset.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sleep', exampleSentence: 'The cat can sleep anywhere it feels warm.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'some', exampleSentence: 'She saved some berries for the morning.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'soon', exampleSentence: 'We will be home soon after the sun sets.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'spell', exampleSentence: 'I learned how to spell my whole name today.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'start', exampleSentence: 'We start each day with a quiet morning walk.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'stay', exampleSentence: 'Please stay close so I can see you.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'still', exampleSentence: 'The pond was still and clear in the morning.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'store', exampleSentence: 'We went to the store to buy fresh fruit.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'story', exampleSentence: 'Dad told us a funny story at bedtime.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'take', exampleSentence: 'Please take this umbrella in case it rains.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'talk', exampleSentence: 'We talk about our day over dinner.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'tall', exampleSentence: 'The tall sunflower grew over the garden gate.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'teach', exampleSentence: 'She loves to teach her little sister new songs.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'tell', exampleSentence: 'I will tell you a secret about the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'than', exampleSentence: 'The new path is shorter than the old one.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'thank', exampleSentence: 'I want to thank you for helping me.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'that', exampleSentence: 'She said that the soup was just right.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'them', exampleSentence: 'Mom made pancakes and we ate all of them.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'then', exampleSentence: 'We washed our hands and then sat down to eat.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'there', exampleSentence: 'There was a little frog sitting on the log.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'they', exampleSentence: 'They walked home together in the afternoon.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'thing', exampleSentence: 'She put each thing back in its proper place.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'think', exampleSentence: 'I think we should bring an umbrella today.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'three', exampleSentence: 'Three little birds sat on the fence post.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'time', exampleSentence: 'It was time to go inside for dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'today', exampleSentence: 'Today we are going to bake banana bread.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'told', exampleSentence: 'She told us the story of the three bears.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'too', exampleSentence: 'I want to come to the park too.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'took', exampleSentence: 'She took a deep breath and smiled.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'train', exampleSentence: 'We rode the train through the mountains.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'truck', exampleSentence: 'The big red truck drove slowly down the street.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'try', exampleSentence: 'She will try her best at whatever she does.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'use', exampleSentence: 'I use a ruler to draw a straight line.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'very', exampleSentence: 'The puppy was very soft and warm.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'walk', exampleSentence: 'We take a long walk after dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'warm', exampleSentence: 'She wrapped herself in a warm blanket.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'wash', exampleSentence: 'We wash our hands before every meal.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'way', exampleSentence: 'She found the best way to tie her shoes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'week', exampleSentence: 'We visit the library once a week.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'well', exampleSentence: 'The garden grew very well after all the rain.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'went', exampleSentence: 'We went to the orchard to pick apples.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'were', exampleSentence: 'The kittens were all sleeping in a pile.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'wet', exampleSentence: 'The dog came in all wet from the rain.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'what', exampleSentence: 'I wonder what surprise is inside the box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'when', exampleSentence: 'Tell me when you are ready to go.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'while', exampleSentence: 'She read a book while waiting for the rain to stop.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'white', exampleSentence: 'The white rabbit disappeared into the tall grass.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'who', exampleSentence: 'Do you know who left these flowers at the door?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'why', exampleSentence: 'She asked why the leaves change color in fall.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'wind', exampleSentence: 'The wind carried the dandelion seeds far away.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'wish', exampleSentence: 'She made a wish and blew out all the candles.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'with', exampleSentence: 'She walked home with her little brother.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'woke', exampleSentence: 'He woke up early to watch the sunrise.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'wood', exampleSentence: 'We gathered wood for the campfire.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'work', exampleSentence: 'They worked together to build the birdhouse.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'yellow', exampleSentence: 'The yellow butterfly landed on a daisy.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'yet', exampleSentence: 'The bread is not ready to eat just yet.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'your', exampleSentence: 'Your drawing looks wonderful on the wall.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'zoo', exampleSentence: 'We saw elephants and giraffes at the zoo.', gradeBand: 'K-1', sourceType: 'curated' },
  // 2-3 — Grade 2–3 Vocabulary List
  { word: 'able', exampleSentence: 'She managed to tie her shoes all by herself for the first time.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'above', exampleSentence: 'The kite floated high above the treetops on a windy day.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'afraid', exampleSentence: 'She held her brother\'s hand when the thunder rumbled outside.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'afternoon', exampleSentence: 'We spent the warm golden hours before dinner playing in the yard.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'again', exampleSentence: 'She liked the story so much she asked to hear it once more.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'age', exampleSentence: 'Dad said she was old enough to join the swim team at seven.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'air', exampleSentence: 'She blew a bubble and watched it float away on the gentle breeze.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'airplane', exampleSentence: 'We watched the big silver jet land smoothly on the runway.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'almost', exampleSentence: 'She had nearly finished her puzzle with just two pieces left.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'alone', exampleSentence: 'The puppy felt better once someone came to sit beside it.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'along', exampleSentence: 'She skipped down the garden path, singing a little song.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'already', exampleSentence: 'By the time we arrived, the cookies were gone and the table was cleared.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'also', exampleSentence: 'My sister loves to draw, and she enjoys painting as well.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'always', exampleSentence: 'Every single morning, Grandpa walks to the bakery for fresh bread.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'animal', exampleSentence: 'The zookeeper showed us how to gently pet the fluffy rabbit.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'another', exampleSentence: 'After finishing the first book, she reached right away for a second one.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'anything', exampleSentence: 'She would do whatever it took to help her little brother feel better.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'around', exampleSentence: 'We rode our bikes through the whole neighborhood before lunch.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'art', exampleSentence: 'She hung her drawing of the rainbow on the classroom wall.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'aunt', exampleSentence: 'My dad\'s sister came to visit from far away and brought us presents.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'balloon', exampleSentence: 'She grabbed the string just as it started to float up into the sky.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'bark', exampleSentence: 'The dog let out a loud sound when it heard footsteps at the gate.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'barn', exampleSentence: 'The horses slept in the big red building at the edge of the farm.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'basket', exampleSentence: 'She filled the wicker container with apples and carried it home from the orchard.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'beach', exampleSentence: 'We built sandcastles and looked for shells by the waves.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'bear', exampleSentence: 'The large furry creature padded quietly through the forest at dawn.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'become', exampleSentence: 'She practiced every day because she wanted to be a great swimmer.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'began', exampleSentence: 'The moment the music started, all the children got up to dance.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'begin', exampleSentence: 'The teacher said we could start our drawings whenever we were ready.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'behind', exampleSentence: 'The little cat hid underneath the sofa and peeked out slowly.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'believe', exampleSentence: 'She trusted that hard work would help her get better at piano.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'below', exampleSentence: 'The fish swam peacefully underneath the lily pads in the pond.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'belt', exampleSentence: 'He threaded the strap through the loops on his jeans.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'better', exampleSentence: 'After a warm bowl of soup and a long nap, she felt much improved.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'birthday', exampleSentence: 'On the special day, she woke up to balloons tied to her chair.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'body', exampleSentence: 'She stretched her arms and legs every morning to feel more awake.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'bones', exampleSentence: 'The dog trotted happily into the yard and dug near the garden fence.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'born', exampleSentence: 'The farmer told us the twin lambs had arrived just that morning.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'bought', exampleSentence: 'Mom came home from the market with a big bag of fresh vegetables.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'bread', exampleSentence: 'Grandma baked a warm golden loaf that filled the house with a wonderful smell.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'bright', exampleSentence: 'The children squinted in the strong sunlight of the summer morning.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'broke', exampleSentence: 'She stepped on her crayon and it snapped right in two.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'brought', exampleSentence: 'Dad came in carrying a box of warm doughnuts for everyone.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'busy', exampleSentence: 'The kitchen hummed with noise as everyone helped prepare the big meal.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'cabin', exampleSentence: 'The little wooden house by the lake had smoke rising from the chimney.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'cage', exampleSentence: 'The hamster spun on its little wheel inside the small wire house.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'camp', exampleSentence: 'We slept in sleeping bags and told stories under the stars.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'can\'t', exampleSentence: 'She stood on her toes but the cookie jar was still just out of reach.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'care', exampleSentence: 'The nurse gently bandaged the child\'s knee with great kindness.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'carry', exampleSentence: 'Dad helps her bring the heavy grocery bags up the porch steps.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'catch', exampleSentence: 'She held out her hands and the ball dropped perfectly into them.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'cattle', exampleSentence: 'The farmer rounded up the cows before the storm rolled in.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'cave', exampleSentence: 'The children shone their flashlights into the dark hollow in the hillside.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'children', exampleSentence: 'The young ones gathered around the teacher to hear the next chapter.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'class', exampleSentence: 'All the students in the room helped decorate for the end-of-year party.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'close', exampleSentence: 'She was nearly at the finish line with just a few steps to go.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'cloth', exampleSentence: 'Grandma cut the soft fabric into squares to make a quilt.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'coal', exampleSentence: 'The old stove was heated by chunks of black rock from the mine.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'color', exampleSentence: 'She chose a deep purple for the sky in her sunset painting.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'corner', exampleSentence: 'They agreed to meet at the spot where the two streets crossed.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'cotton', exampleSentence: 'The fluffy white bolls grew in neat rows across the sunny field.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'cover', exampleSentence: 'She tucked the blanket over the sleeping kitten to keep it warm.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'dark', exampleSentence: 'After the sun went down, the woods became very hard to see through.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'desert', exampleSentence: 'The sandy, sun-baked land stretched for miles with almost no plants.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'didn\'t', exampleSentence: 'She looked everywhere for her other shoe but had no luck finding it.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'dinner', exampleSentence: 'The whole family sat down together for the evening meal.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'dishes', exampleSentence: 'She helped rinse the plates and stack them in the drying rack.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'does', exampleSentence: 'The morning mail usually arrives around nine in the morning.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'done', exampleSentence: 'She put her pencil down, smiled, and turned her paper in.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'don\'t', exampleSentence: 'The sign on the gate said that shoes must stay on at all times.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'dragon', exampleSentence: 'The boy drew a giant fire-breathing lizard creature in his notebook.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'draw', exampleSentence: 'She picked up a pencil and sketched a horse galloping across the page.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'dream', exampleSentence: 'She smiled in her sleep as pictures of faraway adventures filled her mind.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'drink', exampleSentence: 'She poured a cold glass of lemonade and sat on the porch.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'early', exampleSentence: 'The rooster crowed before the sun had even come up over the hills.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'earth', exampleSentence: 'She pressed seeds gently into the dark, rich soil in the garden.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'east', exampleSentence: 'The sun comes up over the hills on the right side of our house each morning.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'eight', exampleSentence: 'She counted out exactly that many crayons and lined them up in a row.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'even', exampleSentence: 'The small bird could fly farther than anyone expected.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'ever', exampleSentence: 'She told us this was the best pie she had tasted in all her life.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'every', exampleSentence: 'Each morning without fail, the dog waited at the door for its walk.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'everyone', exampleSentence: 'Each person in the room cheered when the class won the spelling bee.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'everything', exampleSentence: 'She packed her bag carefully so nothing would be forgotten.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'eyes', exampleSentence: 'She blinked in the bright sunlight and pulled her hat brim down.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'face', exampleSentence: 'She smiled so wide that her cheeks ached a little.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'feeling', exampleSentence: 'She sat quietly for a moment and thought about what was bothering her.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'felt', exampleSentence: 'The warm blanket and cup of cocoa made her seem like herself again.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'few', exampleSentence: 'Only three or four leaves were left on the branch.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'fight', exampleSentence: 'The two puppies tugged and wrestled over the same rope toy.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'fishing', exampleSentence: 'Dad sat on the dock with a line in the water, waiting patiently.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'flying', exampleSentence: 'The geese passed overhead in a perfect V shape.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'follow', exampleSentence: 'She walked close behind her big sister all the way home.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'forest', exampleSentence: 'A narrow path wound through the tall, quiet trees.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'forgot', exampleSentence: 'He ran back inside because he had left his lunch on the counter.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'form', exampleSentence: 'She folded the paper into a graceful shape that looked like a crane.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'found', exampleSentence: 'He reached under the couch and pulled out the missing puzzle piece.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'fourth', exampleSentence: 'She crossed the finish line in the very next spot after third place.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'free', exampleSentence: 'The bird flapped its wings and soared off into the open sky.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'Friday', exampleSentence: 'On the last day of the school week, they always have extra storytime.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'front', exampleSentence: 'She waited on the steps by the door for her grandmother to arrive.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'getting', exampleSentence: 'She noticed the sun was starting to dip lower in the sky.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'given', exampleSentence: 'Each child had been handed a small pot and some seeds to plant.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'grandmother', exampleSentence: 'Mom\'s mother came to visit and brought a trunk full of old photos.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'great', exampleSentence: 'He worked so hard that everyone agreed the project was outstanding.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'grew', exampleSentence: 'The tiny seed they planted in the spring had become a tall sunflower.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'ground', exampleSentence: 'She sat on the cool grass and leaned back to look at the clouds.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'guess', exampleSentence: 'Everyone tried to figure out what was hidden inside the wrapped box.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'hair', exampleSentence: 'She braided her long brown locks and tied a ribbon at the end.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'half', exampleSentence: 'She cut the sandwich down the middle and gave one piece to her friend.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'having', exampleSentence: 'She laughed so hard she nearly spilled her juice.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'head', exampleSentence: 'She balanced a book on top of her hat and walked in a straight line.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'heard', exampleSentence: 'She froze when she noticed a rustling sound coming from the bushes.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'he\'s', exampleSentence: 'We all think he is the best baker in the whole neighborhood.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'heat', exampleSentence: 'The summer air shimmered above the road on the warmest afternoon.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'hello', exampleSentence: 'She waved from across the yard and called out a cheerful greeting.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'high', exampleSentence: 'The kite climbed so far up it looked like a tiny dot in the sky.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'himself', exampleSentence: 'He practiced tying his shoes over and over until he got it right.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'hour', exampleSentence: 'They played board games for sixty whole minutes before dinner.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'hundred', exampleSentence: 'The jar was filled with exactly that many shiny pennies.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'hurry', exampleSentence: 'She grabbed her bag and ran to catch the bus before it left.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'hurt', exampleSentence: 'She bumped her knee on the table but felt better after an ice pack.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'I\'d', exampleSentence: 'If given the choice, I would pick chocolate chip pancakes for breakfast.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'I\'ll', exampleSentence: 'She promised her friend she would help carry the boxes to the car.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'I\'m', exampleSentence: 'She stood up straight and told the class her name with a big smile.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'inches', exampleSentence: 'The seedling had grown four whole units taller since last week.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'isn\'t', exampleSentence: 'She looked out the window and noticed the yard was still covered in snow.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'it\'s', exampleSentence: 'Everyone agrees this is going to be a wonderful day at the park.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'I\'ve', exampleSentence: 'She told the teacher she had already finished reading all three chapters.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'kept', exampleSentence: 'She held onto her library card safely in her coat pocket all winter.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'kids', exampleSentence: 'All the young people on the street played tag until it got dark.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'kind', exampleSentence: 'She shared her snack with the new student without being asked.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'kitten', exampleSentence: 'The tiny baby cat curled into a ball and fell asleep in the sunbeam.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'knew', exampleSentence: 'As soon as she heard the music, she was sure she had heard it before.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'knife', exampleSentence: 'Dad sliced the bread with a long metal blade at the kitchen counter.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'lady', exampleSentence: 'The kind woman at the library always helped find the right books.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'large', exampleSentence: 'The big red wagon could hold all four children easily.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'largest', exampleSentence: 'The biggest pumpkin in the patch won a ribbon at the fair.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'later', exampleSentence: 'She promised to finish the puzzle after dinner.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'leave', exampleSentence: 'She waited until the very last moment to step onto the school bus.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'let\'s', exampleSentence: 'She called out to everyone to come and see what she had discovered.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'letter', exampleSentence: 'She wrote a long message on pink paper and sealed it in an envelope.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'life', exampleSentence: 'The grandmother said her happiest moments were spent by the sea.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'list', exampleSentence: 'She wrote down everything she needed from the store on a long slip of paper.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'living', exampleSentence: 'They set up the cozy room with soft chairs and bookshelves full of stories.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'lovely', exampleSentence: 'The garden smelled wonderful with roses blooming in every corner.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'loving', exampleSentence: 'She gave the puppy a big hug and scratched behind its ears.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'lunch', exampleSentence: 'She opened her bag to find a sandwich, an apple, and a little note from Mom.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'mail', exampleSentence: 'The carrier delivered a stack of letters and a small package.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'making', exampleSentence: 'She was busy putting together a birdhouse with glue and little wooden sticks.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'maybe', exampleSentence: 'She looked at the cloudy sky and wondered if she should bring a jacket.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'mean', exampleSentence: 'She explained the new word by using it in a sentence for the class.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'merry', exampleSentence: 'They sang cheerful holiday songs and danced around the tree.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'might', exampleSentence: 'She packed an umbrella in case showers came later in the day.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'mind', exampleSentence: 'She closed her eyes and thought carefully before choosing an answer.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'money', exampleSentence: 'She put the coins she had earned into her striped savings jar.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'month', exampleSentence: 'Four weeks had passed since she first planted her new garden.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'morning', exampleSentence: 'The smell of toast and warm cocoa drifted through the house at sunrise.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'mouse', exampleSentence: 'A tiny brown creature darted under the baseboard when the light came on.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'mouth', exampleSentence: 'She bit into the crisp red apple and the juice ran down her chin.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'Mr.', exampleSentence: 'Our neighbor, Mr. Chen, waves to us from his porch every morning.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'Mrs.', exampleSentence: 'Their teacher, Mrs. Santos, read the class a new chapter every afternoon.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'Ms.', exampleSentence: 'The librarian, Ms. Rivera, helped the girl pick out three new books.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'music', exampleSentence: 'The whole house filled with the sound of a song playing in the kitchen.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'near', exampleSentence: 'She set her backpack down next to the big oak tree.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'nearly', exampleSentence: 'She was so close to finishing the puzzle — just three more pieces to go.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'never', exampleSentence: 'She had not once eaten a mango before, so this was a first.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'news', exampleSentence: 'The family gathered around to hear what the letter from Grandpa said.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'noise', exampleSentence: 'A loud creak from the staircase woke the puppy from its nap.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'nothing', exampleSentence: 'After checking every drawer and shelf, the mitten was still missing.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'number', exampleSentence: 'She counted the pennies in her jar and wrote the total on a slip of paper.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'o\'clock', exampleSentence: 'When both hands on the clock point straight up, it is exactly twelve.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'often', exampleSentence: 'She and her grandmother visited the farmer\'s market most Saturdays.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'oil', exampleSentence: 'Dad poured a little into the pan before adding the vegetables.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'once', exampleSentence: 'Long ago, in a forest of tall pines, there lived a kind old bear.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'orange', exampleSentence: 'She peeled the round fruit and the sweet smell filled the whole kitchen.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'order', exampleSentence: 'She arranged the crayons from shortest to tallest on her desk.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'own', exampleSentence: 'She was proud to have a little plot in the garden all to herself.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'pair', exampleSentence: 'She found two matching socks at the bottom of the laundry basket.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'paint', exampleSentence: 'She dipped the brush into red and swept a wide arc across the paper.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'paper', exampleSentence: 'She folded the sheet into a hat and put it on her dog.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'party', exampleSentence: 'All her friends came dressed in their best and brought colorful balloons.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'pass', exampleSentence: 'She handed the bowl of mashed potatoes to her grandmother.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'past', exampleSentence: 'They drove by the old mill on the way to the orchard.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'penny', exampleSentence: 'She found a shiny coin on the sidewalk and put it in her pocket.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'people', exampleSentence: 'A crowd gathered to watch the parade go by on the main street.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'person', exampleSentence: 'The kind stranger helped carry the stroller down the steps.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'picture', exampleSentence: 'She taped her drawing to the fridge so everyone could see it.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'place', exampleSentence: 'She found a quiet spot under the big beech tree to read.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'plan', exampleSentence: 'They sketched out everything they needed to build the birdhouse.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'plane', exampleSentence: 'We waved from the window and watched the big craft climb into the clouds.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'please', exampleSentence: 'She asked politely and held the door open for everyone behind her.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'pocket', exampleSentence: 'She tucked the smooth stone into the front of her jeans.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'point', exampleSentence: 'She raised her pencil and pointed to the star on the map.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'poor', exampleSentence: 'The little puppy shivered in the rain until a kind family took it in.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'race', exampleSentence: 'The children lined up at the chalk line and waited for the signal.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'reach', exampleSentence: 'She stood on her toes but still could not touch the top shelf.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'reading', exampleSentence: 'She curled up by the window with a blanket and her favorite book.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'ready', exampleSentence: 'She had her bag packed and her shoes on before Mom even called out.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'real', exampleSentence: 'When the butterfly landed on her hand, she could hardly believe it was true.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'rich', exampleSentence: 'The thick chocolate cake was so sweet it only took one small slice.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'right', exampleSentence: 'She turned and walked straight toward the bakery she could smell ahead.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'river', exampleSentence: 'They sat on the bank and tossed stones into the moving water.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'rocket', exampleSentence: 'At the science fair, their model shot straight up on a stream of air.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'rode', exampleSentence: 'She pedaled her bike all the way to the library without stopping.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'round', exampleSentence: 'She rolled the dough into a flat circle for the pie crust.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'rule', exampleSentence: 'She followed each step carefully and the game went smoothly for everyone.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'running', exampleSentence: 'The puppy sprinted across the yard and leaped into the pile of leaves.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'salt', exampleSentence: 'She shook a little white seasoning over her eggs and stirred the pan.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'says', exampleSentence: 'Our grandmother always tells us to do our very best at whatever we try.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sending', exampleSentence: 'She was putting a birthday card in an envelope to mail to her cousin.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sent', exampleSentence: 'Mom placed a package in the box at the post office to go to Grandma.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'seventh', exampleSentence: 'She counted the seats along the row until she reached her spot.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sew', exampleSentence: 'Grandma threaded a needle and began stitching a patch onto the quilt.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'shall', exampleSentence: 'She asked if everyone would like to meet at the swings after school.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'short', exampleSentence: 'The little table was just the right height for the small children.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'shot', exampleSentence: 'The basketball sailed through the air and swooshed cleanly through the net.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'should', exampleSentence: 'She checked the recipe again to make sure she had added everything.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sight', exampleSentence: 'After the long drive, they finally saw the ocean sparkling ahead.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sister', exampleSentence: 'Her younger sibling crawled over and tried to grab the crayon.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sitting', exampleSentence: 'She was perched on the back porch step, watching the birds at the feeder.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sixth', exampleSentence: 'She counted each chair along the row until she reached her seat.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sled', exampleSentence: 'They dragged it to the top of the hill and took turns zooming down.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'smoke', exampleSentence: 'Thin curls of white rose from the chimney into the cold morning sky.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'soap', exampleSentence: 'She rubbed the bar between her palms until she had a good lather.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'someone', exampleSentence: 'A knock at the door surprised the whole family at dinnertime.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'something', exampleSentence: 'She reached into her coat pocket and felt a small smooth object.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sometime', exampleSentence: 'She promised to bake her famous apple pie when they were all together again.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'song', exampleSentence: 'She hummed the same tune all the way home from school.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sorry', exampleSentence: 'He realized he had bumped into his friend and quickly said he was wrong.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sound', exampleSentence: 'She paused and tilted her head, sure she had heard something in the trees.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'south', exampleSentence: 'We drove toward the warmer part of the country to visit Grandma.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'space', exampleSentence: 'She lay on a blanket and looked up at the stars, imagining faraway worlds.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'spent', exampleSentence: 'She used all her saved-up hours that weekend working in her garden.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sport', exampleSentence: 'She tried every type of outdoor activity until she fell in love with swimming.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'spring', exampleSentence: 'The flowers began to open and the birds came back after the long winter.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'stairs', exampleSentence: 'She held the rail carefully and walked down one step at a time.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'stand', exampleSentence: 'She stepped up to the podium and read her poem to the whole class.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'state', exampleSentence: 'Each student drew the outline of where they lived on the big map.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'step', exampleSentence: 'She lifted her foot high and crossed over the puddle without getting wet.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'stick', exampleSentence: 'She picked up a long thin branch and used it to draw lines in the sand.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'stood', exampleSentence: 'He waited at the corner and watched until the bus disappeared around the bend.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'stopped', exampleSentence: 'She was halfway to the door when she remembered her lunch.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'stove', exampleSentence: 'The pot of soup bubbled gently on the warm burner.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'street', exampleSentence: 'They looked both ways before crossing to the other side.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'strong', exampleSentence: 'She carried the heavy bucket all the way from the well to the garden.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'study', exampleSentence: 'She spread her books across the table and worked quietly for an hour.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'such', exampleSentence: 'Everyone agreed that the sunrise that morning was truly breathtaking.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'sugar', exampleSentence: 'She measured and poured the sweet white crystals into the mixing bowl.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'summer', exampleSentence: 'They swam and made lemonade every day through the hottest months.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'Sunday', exampleSentence: 'On the day after Saturday, the whole family made a big breakfast together.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'supper', exampleSentence: 'They cleared the table and washed up after the evening meal.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'table', exampleSentence: 'She spread a checkered cloth and set out plates for everyone.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'taken', exampleSentence: 'All four seats on the bench were filled by the time she arrived.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'taking', exampleSentence: 'She carefully lifted the glass lid off the pot to check the stew.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'talking', exampleSentence: 'The two friends sat on the porch steps, sharing stories until dark.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'teacher', exampleSentence: 'The kind woman at the front of the room helped each student with their project.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'team', exampleSentence: 'All five players worked together and helped each other all game long.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'teeth', exampleSentence: 'She brushed carefully, both top and bottom rows, before bed each night.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'tenth', exampleSentence: 'She counted each card in the stack until she reached the last one.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'that\'s', exampleSentence: 'She looked at her finished painting and thought it turned out really nicely.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'their', exampleSentence: 'The two friends grabbed backpacks and set off down the road together.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'these', exampleSentence: 'She picked up a handful of shells from the sand and put them in her pocket.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'thinking', exampleSentence: 'She tapped her pencil on her chin and stared out the window.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'third', exampleSentence: 'She crossed the finish line right behind the first two runners.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'those', exampleSentence: 'She pointed to the books on the far shelf and asked to borrow them.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'thought', exampleSentence: 'She was sure she had left her mitten somewhere near the door.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'throw', exampleSentence: 'She wound up and tossed the ball in a perfect arc toward the catcher.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'tonight', exampleSentence: 'As the sun went down, they gathered for a bonfire in the yard.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'trade', exampleSentence: 'She swapped her apple for her friend\'s orange at lunch.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'trick', exampleSentence: 'The magician showed the children how to make a coin disappear.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'trip', exampleSentence: 'They packed their bags the night before the long drive to Grandma\'s house.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'trying', exampleSentence: 'She kept practicing the knot over and over until she finally got it right.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'turn', exampleSentence: 'She stepped to the back of the line to wait for her chance to go.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'twelve', exampleSentence: 'She counted out exactly that many cards and dealt them around the table.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'twenty', exampleSentence: 'The jar held more coins than she expected — a whole score of them.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'uncle', exampleSentence: 'Dad\'s brother visited for the weekend and taught them how to make kites.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'under', exampleSentence: 'The cat squeezed beneath the bed and curled up behind the suitcases.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'upon', exampleSentence: 'She climbed to the top of the ladder and could see all the way to the valley.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'wagon', exampleSentence: 'She loaded the little cart with her stuffed animals and pulled it around the yard.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'wait', exampleSentence: 'She took a deep breath and stayed patient while the bread finished baking.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'walking', exampleSentence: 'She hummed softly as she made her way through the autumn leaves.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'wasn\'t', exampleSentence: 'She looked all around but there was no sign of rain in the sky.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'watch', exampleSentence: 'She stood at the window and waited for the parade to pass by.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'weather', exampleSentence: 'She looked out the window each morning to decide which jacket to wear.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'we\'re', exampleSentence: 'Everyone was excited about the trip to the mountains next Saturday.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'west', exampleSentence: 'They drove toward where the sun was setting, into the painted orange sky.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'wheat', exampleSentence: 'The golden grain swayed gently in the breeze across the whole field.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'where', exampleSentence: 'She retraced her steps, looking for the spot she had last seen her mittens.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'which', exampleSentence: 'She stood at the bookshelf, deciding between two different stories.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'wife', exampleSentence: 'The farmer\'s partner helped tend the garden every morning before sunrise.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'wild', exampleSentence: 'The horses galloped across the open meadow without any fences to stop them.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'win', exampleSentence: 'She worked hard all season because she wanted her team to take the championship.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'window', exampleSentence: 'She pressed her nose to the glass and watched snowflakes land on the sill.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'winter', exampleSentence: 'She wrapped her scarf tight and left tiny boot prints in the fresh snow.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'without', exampleSentence: 'She forgot her umbrella but managed to stay almost completely dry.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'woman', exampleSentence: 'The kind neighbor always brought over soup whenever someone on the street was unwell.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'won', exampleSentence: 'The whole team cheered and hugged when they heard the final score.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'won\'t', exampleSentence: 'She shook her head quietly and chose to stay home and read instead.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'wool', exampleSentence: 'Grandma knitted a warm scarf from the soft strands she had spun herself.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'word', exampleSentence: 'She looked up the meaning and then used it in three different sentences.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'working', exampleSentence: 'She stayed at her desk long after everyone else had packed up to leave.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'world', exampleSentence: 'She opened the atlas and dreamed about all the places she would visit someday.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'would', exampleSentence: 'She told her little brother she was happy to read to him whenever he wanted.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'wrong', exampleSentence: 'She noticed her answer differed from the key and went back to check her work.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'yard', exampleSentence: 'She raked the autumn leaves into a pile and then jumped right in.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'year', exampleSentence: 'At the end of twelve months, they planted a new tree to mark the time.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'yesterday', exampleSentence: 'She told her grandma about the butterfly she had seen the day before.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'you\'re', exampleSentence: 'She wrote on the card that her friend was the kindest person she knew.', gradeBand: '2-3', sourceType: 'curated' },
  // 4-5
  { word: 'because', exampleSentence: 'She brought an umbrella because it might rain.', gradeBand: '4-5', sourceType: 'curated' },
  { word: 'friend', exampleSentence: 'A good friend listens when you need to talk.', gradeBand: '4-5', sourceType: 'curated' },
  { word: 'school', exampleSentence: 'We walk to school together every morning.', gradeBand: '4-5', sourceType: 'curated' },
  { word: 'house', exampleSentence: 'Their house has a big garden in the back.', gradeBand: '4-5', sourceType: 'curated' },
  { word: 'family', exampleSentence: 'Our family gathers for dinner on Sundays.', gradeBand: '4-5', sourceType: 'curated' },
];
