import type { SentenceBankEntry } from './types';

export const SENTENCE_BANK: SentenceBankEntry[] = [
  // K-1
  { word: 'cat', exampleSentence: 'The cat sat on the soft rug.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'dog', exampleSentence: 'My dog loves to play in the yard.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'big', exampleSentence: 'The big elephant splashed in the water.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'run', exampleSentence: 'We run to the park after school.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'jump', exampleSentence: 'She can jump over the puddle.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'day', exampleSentence: 'It was a sunny day at the beach.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'night', exampleSentence: 'Stars shine in the sky at night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'rain', exampleSentence: 'The rain made puddles on the sidewalk.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'snow', exampleSentence: 'We built a snowman in the fluffy snow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hand', exampleSentence: 'She raised her hand to answer the question.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'girl', exampleSentence: 'The girl read a book under the tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fish', exampleSentence: 'We saw a colorful fish in the pond.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bird', exampleSentence: 'A little bird sang outside the window.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'tree', exampleSentence: 'An apple grows on that tall tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'help', exampleSentence: 'Can you help me carry these books?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'like', exampleSentence: 'I like to read before bedtime.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'love', exampleSentence: 'We love spending time with our family.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'want', exampleSentence: 'Do you want a glass of water?', gradeBand: 'K-1', sourceType: 'curated' },
  // K-1 — Reading Rockets Basic Spelling Vocabulary List, Grade 1
  { word: 'a', exampleSentence: 'I see a big red ball.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'all', exampleSentence: 'We eat all of the grapes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'am', exampleSentence: 'I am six years old.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'and', exampleSentence: 'I have a cat and a dog.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'at', exampleSentence: 'We are at the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ball', exampleSentence: 'The red ball rolls down the hill.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'be', exampleSentence: 'I want to be a teacher.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bed', exampleSentence: 'I sleep in my warm bed.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'box', exampleSentence: 'The toys are in the box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'boy', exampleSentence: 'The boy kicks the ball.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'but', exampleSentence: 'I want to play, but it is raining.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'came', exampleSentence: 'My friend came over to play.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'can', exampleSentence: 'We put the soup in a can.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'car', exampleSentence: 'Dad drives the car to the store.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'come', exampleSentence: 'Please come and sit with me.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'cow', exampleSentence: 'The cow eats grass in the field.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'dad', exampleSentence: 'My dad reads me a story.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'did', exampleSentence: 'I did my homework after lunch.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'do', exampleSentence: 'I do my chores every day.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fat', exampleSentence: 'The fat pig rolls in the mud.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'for', exampleSentence: 'This gift is for you.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fun', exampleSentence: 'We have fun at the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'get', exampleSentence: 'I get a glass of water.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'go', exampleSentence: 'We go to school on the bus.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'good', exampleSentence: 'She is a good friend.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'got', exampleSentence: 'I got a new toy today.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'had', exampleSentence: 'We had soup for lunch.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hat', exampleSentence: 'I wear a warm hat in the snow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'he', exampleSentence: 'He runs to the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hen', exampleSentence: 'The hen sits on her eggs.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'here', exampleSentence: 'Come and sit here with me.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'him', exampleSentence: 'I give the ball to him.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'his', exampleSentence: 'He puts on his shoes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'home', exampleSentence: 'We walk home after school.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hot', exampleSentence: 'The soup is too hot to eat.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'I', exampleSentence: 'I like to ride my bike.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'if', exampleSentence: 'We can play if it stops raining.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'in', exampleSentence: 'The cat sleeps in the box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'into', exampleSentence: 'The dog jumps into the water.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'is', exampleSentence: 'The sky is blue today.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'it', exampleSentence: 'I see a ball and kick it.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'its', exampleSentence: 'The dog wags its tail.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'let', exampleSentence: 'Let me help you carry that.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'look', exampleSentence: 'Look at the bird in the tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'man', exampleSentence: 'The man waters his garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'me', exampleSentence: 'Can you give the book to me?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'mom', exampleSentence: 'My mom makes pancakes for breakfast.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'my', exampleSentence: 'My shoes are by the door.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'no', exampleSentence: 'There are no clouds in the sky.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'not', exampleSentence: 'The water is not cold.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'of', exampleSentence: 'I drink a glass of milk.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'old', exampleSentence: 'My shoes are old and worn.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'on', exampleSentence: 'The cat sits on the rug.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'one', exampleSentence: 'I have one apple in my bag.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'out', exampleSentence: 'We go out to play in the yard.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'pan', exampleSentence: 'Mom cooks eggs in the pan.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'pet', exampleSentence: 'My pet cat likes to nap.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'pig', exampleSentence: 'The little pig eats from a bowl.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ran', exampleSentence: 'We ran around the playground.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'rat', exampleSentence: 'A small rat hides under the box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'red', exampleSentence: 'I have a red wagon.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ride', exampleSentence: 'I ride my bike to the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sat', exampleSentence: 'We sat under the big tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'see', exampleSentence: 'I can see the moon at night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'she', exampleSentence: 'She paints a picture of a cat.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sit', exampleSentence: 'Please sit in your chair.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'six', exampleSentence: 'I have six crayons in my box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'so', exampleSentence: 'The sun is so bright today.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'stop', exampleSentence: 'We stop at the red light.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sun', exampleSentence: 'The sun is warm on my face.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ten', exampleSentence: 'I can count to ten.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'the', exampleSentence: 'The dog runs in the yard.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'this', exampleSentence: 'This apple tastes sweet.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'to', exampleSentence: 'We walk to the park together.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'top', exampleSentence: 'The spinning top falls on its side.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'toy', exampleSentence: 'My favorite toy is a soft bear.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'two', exampleSentence: 'I have two red apples.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'up', exampleSentence: 'The balloon floats up into the sky.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'us', exampleSentence: 'Mom reads a story to us.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'was', exampleSentence: 'The sky was clear last night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'we', exampleSentence: 'We play in the park together.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'yes', exampleSentence: 'Yes, I would like some water.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'you', exampleSentence: 'Can you help me find my shoes?', gradeBand: 'K-1', sourceType: 'curated' },
  // 2-3
  { word: 'play', exampleSentence: 'The children play outside after lunch.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'book', exampleSentence: 'She borrowed a book from the library.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'water', exampleSentence: 'Remember to drink plenty of water each day.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'small', exampleSentence: 'A small kitten hid under the chair.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'cold', exampleSentence: 'Put on your coat because it is cold outside.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'fast', exampleSentence: 'The fast rabbit reached the finish line first.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'slow', exampleSentence: 'The slow turtle finished the race last.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'flower', exampleSentence: 'She planted a flower in the garden.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'happy', exampleSentence: 'Everyone felt happy on the last day of school.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'learn', exampleSentence: 'We learn something new every day.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'write', exampleSentence: 'Please write your name at the top of the page.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'mother', exampleSentence: 'My mother makes the best soup.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'father', exampleSentence: 'Her father teaches at the school nearby.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'about', exampleSentence: 'We read a book about frogs and ponds.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'add', exampleSentence: 'I can add two and three to get five.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'after', exampleSentence: 'We went for a walk after dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ago', exampleSentence: 'We visited the farm a long time ago.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'an', exampleSentence: 'She found an acorn under the oak tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'any', exampleSentence: 'Do you have any apples left?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'apple', exampleSentence: 'She packed an apple in her lunch box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'are', exampleSentence: 'The ducks are swimming in the pond.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'as', exampleSentence: 'The puppy is as soft as a pillow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ask', exampleSentence: 'You can ask me if you need help.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ate', exampleSentence: 'We ate soup and bread for dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'away', exampleSentence: 'The butterfly flew away into the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'baby', exampleSentence: 'The baby laughed and clapped her hands.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'back', exampleSentence: 'Put the book back on the shelf.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bad', exampleSentence: 'The bad weather kept us inside all day.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bag', exampleSentence: 'She packed her bag for the trip to school.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'base', exampleSentence: 'The lamp sits on a round wooden base.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'bat', exampleSentence: 'He picked up the bat and got ready to swing.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bee', exampleSentence: 'A yellow bee landed on the flower.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'been', exampleSentence: 'Have you ever been to a farm before?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'before', exampleSentence: 'Brush your teeth before you go to sleep.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'being', exampleSentence: 'She is being very kind to her little brother.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'best', exampleSentence: 'My dog is my very best friend.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bike', exampleSentence: 'She rode her bike down the winding path.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bill', exampleSentence: 'The duck had a wide orange bill.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'black', exampleSentence: 'The black cat sat on the warm porch.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'blue', exampleSentence: 'The sky was clear and bright blue.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'boat', exampleSentence: 'We watched a little boat sail on the lake.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'both', exampleSentence: 'Both puppies wanted to play with the ball.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bring', exampleSentence: 'Please bring your raincoat to school today.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'brother', exampleSentence: 'My brother and I play in the yard together.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'brown', exampleSentence: 'A brown rabbit hopped into the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'bus', exampleSentence: 'We ride the bus to school every morning.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'buy', exampleSentence: 'We stop at the store to buy fresh bread.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'by', exampleSentence: 'The dog slept by the warm fireplace.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'cake', exampleSentence: 'She blew out the candles on her birthday cake.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'call', exampleSentence: 'I will call you when I get home.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'candy', exampleSentence: 'She saved one piece of candy for later.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'change', exampleSentence: 'The leaves change color in the fall.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'child', exampleSentence: 'Every child in the class got a new book.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'city', exampleSentence: 'We drove through the busy city on our trip.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'clean', exampleSentence: 'Please clean up your toys before dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'club', exampleSentence: 'She joined the art club at school.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'coat', exampleSentence: 'Button up your coat before going outside.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'coming', exampleSentence: 'The train is coming around the bend.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'corn', exampleSentence: 'We picked fresh corn from the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'could', exampleSentence: 'She could hear the birds singing outside.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'cry', exampleSentence: 'The baby would cry when she was hungry.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'cup', exampleSentence: 'He poured milk into a blue cup.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'cut', exampleSentence: 'She cut the paper into small stars.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'daddy', exampleSentence: 'Daddy reads me a story every night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'dear', exampleSentence: 'She wrote to her dear grandmother every month.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'deep', exampleSentence: 'The well is very deep and full of cool water.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'deer', exampleSentence: 'A deer stood quietly in the tall grass.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'doing', exampleSentence: 'What are you doing with all those crayons?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'doll', exampleSentence: 'She tucked her doll into a little blanket.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'door', exampleSentence: 'Please close the door so the cat stays inside.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'down', exampleSentence: 'The leaf floated slowly down from the branch.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'dress', exampleSentence: 'She wore a yellow dress to the picnic.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'drive', exampleSentence: 'We drive past the farm on the way to town.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'drop', exampleSentence: 'Be careful not to drop the eggs.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'dry', exampleSentence: 'She used a towel to dry her hands.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'duck', exampleSentence: 'A fluffy duck waddled to the edge of the pond.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'each', exampleSentence: 'Each child got a turn to read aloud.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'eat', exampleSentence: 'We eat together as a family every evening.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'eating', exampleSentence: 'The rabbit was eating a carrot in the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'egg', exampleSentence: 'She cracked an egg into the mixing bowl.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'end', exampleSentence: 'We sat at the end of the long table.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fall', exampleSentence: 'Red and yellow leaves fall from the trees.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'far', exampleSentence: 'The mountains look small because they are so far away.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'farm', exampleSentence: 'We visited a farm and saw pigs and cows.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'feed', exampleSentence: 'We feed the ducks bread at the pond.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'feel', exampleSentence: 'The soft blanket makes me feel cozy.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'feet', exampleSentence: 'Mud squished between her toes and under her feet.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fell', exampleSentence: 'A ripe apple fell from the tree.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'find', exampleSentence: 'Can you find the hidden star in the picture?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fine', exampleSentence: 'The weather was fine for a walk in the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fire', exampleSentence: 'The fireplace kept the whole room warm.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'first', exampleSentence: 'She was the first to finish her drawing.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'five', exampleSentence: 'I counted five ducks on the pond.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fix', exampleSentence: 'Dad helped me fix the broken wheel on my toy.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'flag', exampleSentence: 'The flag waved in the gentle breeze.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'floor', exampleSentence: 'The cat curled up on the warm floor.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fly', exampleSentence: 'We watched a butterfly fly from flower to flower.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'food', exampleSentence: 'We packed food for our picnic in the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'foot', exampleSentence: 'She put on one sock on each foot.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'four', exampleSentence: 'The puppy had four tiny white paws.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'fox', exampleSentence: 'A red fox peeked out from behind the bushes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'from', exampleSentence: 'We got a postcard from our grandparents.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'full', exampleSentence: 'My backpack is full of books and crayons.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'funny', exampleSentence: 'The clown made a funny face to make us laugh.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'game', exampleSentence: 'We played a card game after dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'gas', exampleSentence: 'Dad stopped to put gas in the car.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'gave', exampleSentence: 'Grandma gave us a warm hug hello.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'give', exampleSentence: 'She wanted to give her friend a card.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'glad', exampleSentence: 'I am glad you came to visit us.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'goat', exampleSentence: 'A friendly goat ate grass near the fence.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'goes', exampleSentence: 'The sun goes down behind the hills each evening.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'going', exampleSentence: 'We are going to the library after lunch.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'gold', exampleSentence: 'The autumn leaves turned orange and gold.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'gone', exampleSentence: 'By morning the snow was already gone.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'grade', exampleSentence: 'She moved up to the next grade at school.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'grass', exampleSentence: 'We lay on the soft grass and looked at clouds.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'green', exampleSentence: 'The frogs sat on the green lily pads.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'grow', exampleSentence: 'We planted seeds and watched them grow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hard', exampleSentence: 'The frozen ground was hard under our boots.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'has', exampleSentence: 'My dog has soft brown ears.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'have', exampleSentence: 'We have a garden full of tomatoes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hear', exampleSentence: 'I can hear the birds singing in the morning.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hill', exampleSentence: 'We rolled down the grassy hill together.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hit', exampleSentence: 'She hit the ball with the wooden bat.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hold', exampleSentence: 'Please hold my hand when we cross the street.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hole', exampleSentence: 'A small rabbit looked out from its hole.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hop', exampleSentence: 'The bunny likes to hop around the yard.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'hope', exampleSentence: 'I hope the sun comes out tomorrow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'horse', exampleSentence: 'The horse trotted slowly around the field.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'how', exampleSentence: 'She showed me how to tie my shoes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ice', exampleSentence: 'We saw ducks walking on the thin ice.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'inch', exampleSentence: 'The tiny worm was less than one inch long.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'inside', exampleSentence: 'We came inside when it started to rain.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'job', exampleSentence: 'Everyone had a job to do to set the table.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'just', exampleSentence: 'I just finished reading my favorite book.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'keep', exampleSentence: 'Please keep your room clean and tidy.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'king', exampleSentence: 'The story was about a kind and gentle king.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'know', exampleSentence: 'I know all the words to that song.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'lake', exampleSentence: 'We paddled a canoe across the quiet lake.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'land', exampleSentence: 'We watched the plane land gently on the runway.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'last', exampleSentence: 'She saved the last cookie for her brother.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'late', exampleSentence: 'The bus was late because of the heavy rain.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'lay', exampleSentence: 'The cat likes to lay in the patch of sunlight.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'left', exampleSentence: 'Turn left at the corner to find the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'leg', exampleSentence: 'The grasshopper jumped with its long back leg.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'light', exampleSentence: 'The morning light came softly through the curtain.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'line', exampleSentence: 'We stood in a line to get our books.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'little', exampleSentence: 'A little mouse peeked out from behind the wall.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'live', exampleSentence: 'We live close to the park and the library.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'lives', exampleSentence: 'The friendly cat lives next door to us.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'long', exampleSentence: 'The path through the woods was long and winding.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'looking', exampleSentence: 'She was looking for her lost mitten.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'lost', exampleSentence: 'He found his lost toy under the bed.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'lot', exampleSentence: 'We had a lot of fun at the fair.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'mad', exampleSentence: 'He was a little mad but calmed down quickly.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'made', exampleSentence: 'She made a card for her grandmother.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'make', exampleSentence: 'Let us make a birdhouse out of wood.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'many', exampleSentence: 'There were many stars in the clear night sky.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'meat', exampleSentence: 'We had soup with vegetables and a little meat.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'men', exampleSentence: 'The men worked together to build the garden fence.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'met', exampleSentence: 'She met her new friend at the park.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'mile', exampleSentence: 'The farm is about a mile down the road.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'milk', exampleSentence: 'She poured a tall glass of cold milk.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'mine', exampleSentence: 'That red crayon is mine.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'miss', exampleSentence: 'I miss my grandpa when he travels far away.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'moon', exampleSentence: 'The moon was round and bright last night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'more', exampleSentence: 'May I have a little more soup, please?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'most', exampleSentence: 'Most of the apples were ripe and ready.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'move', exampleSentence: 'We had to move the table to make room.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'much', exampleSentence: 'Thank you so much for helping me.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'must', exampleSentence: 'You must wash your hands before eating.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'myself', exampleSentence: 'I made the card all by myself.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'nail', exampleSentence: 'Dad used a hammer and nail to hang the picture.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'name', exampleSentence: 'Write your name at the top of the page.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'need', exampleSentence: 'We need to pack our bags before the trip.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'new', exampleSentence: 'She got a new book from the library.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'next', exampleSentence: 'We will bake cookies next weekend.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'nice', exampleSentence: 'It was nice to see everyone at the gathering.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'nine', exampleSentence: 'There were nine ducklings following the mother duck.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'north', exampleSentence: 'We drove north to see the mountains.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'now', exampleSentence: 'It is time to go inside now.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'nut', exampleSentence: 'The squirrel found a nut and carried it home.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'off', exampleSentence: 'She turned off the light and went to sleep.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'only', exampleSentence: 'There was only one slice of pie left.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'open', exampleSentence: 'She pulled the door open with both hands.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'or', exampleSentence: 'Would you like milk or water with dinner?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'other', exampleSentence: 'The other children waited at the gate.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'our', exampleSentence: 'We planted flowers in our garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'outside', exampleSentence: 'Let us go outside and play in the leaves.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'over', exampleSentence: 'The cat jumped over the garden wall.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'page', exampleSentence: 'She turned the page and kept reading.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'park', exampleSentence: 'We had a picnic at the park on Sunday.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'part', exampleSentence: 'We each did our part to clean up.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'pay', exampleSentence: 'Mom let me pay for the apples at the market.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'pick', exampleSentence: 'We went to pick strawberries at the farm.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'plant', exampleSentence: 'She helped plant seeds in the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'playing', exampleSentence: 'The children were playing in the fallen leaves.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'pony', exampleSentence: 'She gently brushed the pony\'s soft mane.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'post', exampleSentence: 'He put the letter in the post box.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'pull', exampleSentence: 'She had to pull hard to open the drawer.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'put', exampleSentence: 'Please put your shoes by the door.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'rabbit', exampleSentence: 'A white rabbit nibbled on the clover.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'read', exampleSentence: 'Dad read us a chapter every night.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'rest', exampleSentence: 'The puppy curled up for a rest in the sunshine.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'riding', exampleSentence: 'She waved as she was riding past on her bike.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'road', exampleSentence: 'We walked along the quiet country road.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'rock', exampleSentence: 'She found a smooth shiny rock by the stream.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'room', exampleSentence: 'Her room was cozy with soft rugs and pillows.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'said', exampleSentence: 'She said hello to every neighbor on the street.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'same', exampleSentence: 'We wore the same color shirt to the picnic.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sang', exampleSentence: 'The birds sang sweetly in the morning.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'saw', exampleSentence: 'I saw a rainbow after the rain.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'say', exampleSentence: 'What did she say when she opened the gift?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sea', exampleSentence: 'We collected shells at the edge of the sea.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'seat', exampleSentence: 'She found a cozy seat by the window.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'seem', exampleSentence: 'The kittens seem happy in their new home.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'seen', exampleSentence: 'I have never seen so many fireflies at once.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'send', exampleSentence: 'Let us send a card to our grandparents.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'set', exampleSentence: 'We set the table before everyone arrived.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'seven', exampleSentence: 'She counted seven eggs in the nest.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sheep', exampleSentence: 'The fluffy sheep grazed in the meadow.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'ship', exampleSentence: 'We watched the big ship sail out to sea.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'shoe', exampleSentence: 'She tied the bow on her shoe.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'show', exampleSentence: 'Let me show you how to fold a paper crane.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sick', exampleSentence: 'He stayed home with warm soup when he felt sick.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'side', exampleSentence: 'She planted flowers on each side of the path.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sing', exampleSentence: 'We love to sing songs on long car rides.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sky', exampleSentence: 'The sky turned pink and orange at sunset.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'sleep', exampleSentence: 'The cat can sleep anywhere it feels warm.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'some', exampleSentence: 'She saved some berries for the morning.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'soon', exampleSentence: 'We will be home soon after the sun sets.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'spell', exampleSentence: 'I learned how to spell my whole name today.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'start', exampleSentence: 'We start each day with a quiet morning walk.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'stay', exampleSentence: 'Please stay close so I can see you.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'still', exampleSentence: 'The pond was still and clear in the morning.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'store', exampleSentence: 'We went to the store to buy fresh fruit.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'story', exampleSentence: 'Dad told us a funny story at bedtime.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'take', exampleSentence: 'Please take this umbrella in case it rains.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'talk', exampleSentence: 'We talk about our day over dinner.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'tall', exampleSentence: 'The tall sunflower grew over the garden gate.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'teach', exampleSentence: 'She loves to teach her little sister new songs.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'tell', exampleSentence: 'I will tell you a secret about the garden.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'than', exampleSentence: 'The new path is shorter than the old one.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'thank', exampleSentence: 'I want to thank you for helping me.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'that', exampleSentence: 'She said that the soup was just right.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'them', exampleSentence: 'Mom made pancakes and we ate all of them.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'then', exampleSentence: 'We washed our hands and then sat down to eat.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'there', exampleSentence: 'There was a little frog sitting on the log.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'they', exampleSentence: 'They walked home together in the afternoon.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'thing', exampleSentence: 'She put each thing back in its proper place.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'think', exampleSentence: 'I think we should bring an umbrella today.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'three', exampleSentence: 'Three little birds sat on the fence post.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'time', exampleSentence: 'It was time to go inside for dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'today', exampleSentence: 'Today we are going to bake banana bread.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'told', exampleSentence: 'She told us the story of the three bears.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'too', exampleSentence: 'I want to come to the park too.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'took', exampleSentence: 'She took a deep breath and smiled.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'train', exampleSentence: 'We rode the train through the mountains.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'truck', exampleSentence: 'The big red truck drove slowly down the street.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'try', exampleSentence: 'She will try her best at whatever she does.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'use', exampleSentence: 'I use a ruler to draw a straight line.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'very', exampleSentence: 'The puppy was very soft and warm.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'walk', exampleSentence: 'We take a long walk after dinner.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'warm', exampleSentence: 'She wrapped herself in a warm blanket.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'wash', exampleSentence: 'We wash our hands before every meal.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'way', exampleSentence: 'She found the best way to tie her shoes.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'week', exampleSentence: 'We visit the library once a week.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'well', exampleSentence: 'The garden grew very well after all the rain.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'went', exampleSentence: 'We went to the orchard to pick apples.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'were', exampleSentence: 'The kittens were all sleeping in a pile.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'wet', exampleSentence: 'The dog came in all wet from the rain.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'what', exampleSentence: 'I wonder what surprise is inside the box.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'when', exampleSentence: 'Tell me when you are ready to go.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'while', exampleSentence: 'She read a book while waiting for the rain to stop.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'white', exampleSentence: 'The white rabbit disappeared into the tall grass.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'who', exampleSentence: 'Do you know who left these flowers at the door?', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'why', exampleSentence: 'She asked why the leaves change color in fall.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'wind', exampleSentence: 'The wind carried the dandelion seeds far away.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'wish', exampleSentence: 'She made a wish and blew out all the candles.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'with', exampleSentence: 'She walked home with her little brother.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'woke', exampleSentence: 'He woke up early to watch the sunrise.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'wood', exampleSentence: 'We gathered wood for the campfire.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'work', exampleSentence: 'They worked together to build the birdhouse.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'yellow', exampleSentence: 'The yellow butterfly landed on a daisy.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'yet', exampleSentence: 'The bread is not ready to eat just yet.', gradeBand: '2-3', sourceType: 'curated' },
  { word: 'your', exampleSentence: 'Your drawing looks wonderful on the wall.', gradeBand: 'K-1', sourceType: 'curated' },
  { word: 'zoo', exampleSentence: 'We saw elephants and giraffes at the zoo.', gradeBand: 'K-1', sourceType: 'curated' },
  // 4-5
  { word: 'because', exampleSentence: 'She brought an umbrella because it might rain.', gradeBand: '4-5', sourceType: 'curated' },
  { word: 'friend', exampleSentence: 'A good friend listens when you need to talk.', gradeBand: '4-5', sourceType: 'curated' },
  { word: 'school', exampleSentence: 'We walk to school together every morning.', gradeBand: '4-5', sourceType: 'curated' },
  { word: 'house', exampleSentence: 'Their house has a big garden in the back.', gradeBand: '4-5', sourceType: 'curated' },
  { word: 'family', exampleSentence: 'Our family gathers for dinner on Sundays.', gradeBand: '4-5', sourceType: 'curated' },
];
