import type { ReviewWordEntry } from './types';

export const REVIEW_WORDS: ReviewWordEntry[] = [
  {
    word: 'minute',
    reason: 'Heteronym: "MIN-it" (unit of time) vs "my-NOOT" (very small)',
    recommendation: 'Skip. TTS will produce "MIN-it" for isolated word; sentence context may force "my-NOOT" reading.',
    status: 'avoid',
  },
  {
    word: 'live',
    reason: 'Heteronym: verb "lɪv" (to live somewhere) vs adjective "laɪv" (a live show)',
    recommendation: 'Skip. Cannot write a single sentence that unambiguously matches TTS isolated pronunciation.',
    status: 'avoid',
    notes: 'Was briefly in the bank; removed in audit pass.',
  },
  {
    word: 'read',
    reason: 'Heteronym: present "reed" vs past tense "red"',
    recommendation: 'Skip. Sentence would force one pronunciation, but isolated TTS pronunciation is ambiguous.',
    status: 'avoid',
    notes: 'Was briefly in the bank (past-tense usage); removed in audit pass.',
  },
  {
    word: 'wind',
    reason: 'Heteronym: noun "wɪnd" (the wind blows) vs verb "waɪnd" (to wind a clock)',
    recommendation: 'Skip. Too ambiguous for TTS.',
    status: 'avoid',
    notes: 'Was briefly in the bank; removed in audit pass.',
  },
  {
    word: 'close',
    reason: 'Heteronym: verb "kloʊz" (to close a door) vs adjective "kloʊs" (sitting close)',
    recommendation: 'Skip. TTS may produce wrong pronunciation.',
    status: 'avoid',
    notes: 'Was briefly in the bank; removed in audit pass.',
  },
  {
    word: 'Saturday',
    reason: 'Proper noun (day of week). Content standards prohibit proper nouns in the word field.',
    recommendation: 'Remove. The word "Saturday" is fine as content in sentences, but not as a spelling test target.',
    status: 'avoid',
    notes: 'Was in the bank; removed in audit pass.',
  },
  {
    word: 'tear',
    reason: 'Heteronym: noun "tɪr" (a tear from crying) vs verb "tɛr" (to tear paper)',
    recommendation: 'Skip.',
    status: 'avoid',
  },
  {
    word: 'lead',
    reason: 'Heteronym: verb "liːd" (to lead the group) vs noun "lɛd" (the metal lead)',
    recommendation: 'Skip.',
    status: 'avoid',
  },
  {
    word: 'row',
    reason: 'Heteronym: noun "roʊ" (a row of seats) vs verb "raʊ" (British: a quarrel)',
    recommendation: 'Skip in British-aware contexts. US usage "roʊ" only may be safe-to-add with careful sentence.',
    status: 'needs-review',
    notes: 'In US curriculum the verb sense (to row a boat) is unambiguous "roʊ". Consider adding with a boat sentence.',
  },
  {
    word: 'wound',
    reason: 'Heteronym: noun "wuːnd" (an injury) vs past tense "waʊnd" (wound up the clock)',
    recommendation: 'Skip.',
    status: 'avoid',
  },
  {
    word: 'bow',
    reason: 'Heteronym: noun "boʊ" (bow and arrow) vs verb "baʊ" (to bow your head)',
    recommendation: 'Skip.',
    status: 'avoid',
  },
  {
    word: 'sow',
    reason: 'Heteronym: verb "soʊ" (to sow seeds) vs noun "saʊ" (a female pig)',
    recommendation: 'Skip.',
    status: 'avoid',
  },
  {
    word: 'does',
    reason: 'Irregular pronunciation: "dʌz" not "doʊz" — may trip up TTS or children',
    recommendation: 'Safe to add. TTS reliably produces "dʌz". Sentence should use clearly as third-person singular verb.',
    status: 'safe-to-add',
    notes: 'Example: "The dog does tricks when we give it a treat."',
  },
  {
    word: 'hour',
    reason: 'Silent H: "aʊər" — children may misspell thinking it sounds like "our"',
    recommendation: 'Safe to add. Pronunciation is unambiguous; TTS handles it reliably.',
    status: 'safe-to-add',
    notes: 'Common sight word, worth adding. Example: "We waited about an hour for the cookies to bake."',
  },
  {
    word: 'eight',
    reason: 'Unusual spelling for /eɪt/ sound; often on spelling lists',
    recommendation: 'Safe to add. Pronunciation is unambiguous.',
    status: 'safe-to-add',
    notes: 'Example: "There were eight chicks in the nest."',
  },
  {
    word: 'people',
    reason: 'Very common word, possibly missing from bank',
    recommendation: 'Safe to add if not present.',
    status: 'safe-to-add',
    notes: 'Example: "Many people gathered in the town square to watch the parade."',
  },
  {
    word: 'Mr.',
    reason: 'Honorific abbreviation. Any sentence naturally requires a proper name after it, violating the no-proper-nouns rule.',
    recommendation: 'Skip. The title itself is not a standalone spelling target suitable for the bank.',
    status: 'avoid',
    notes: 'Was briefly added in an expansion pass; removed in audit.',
  },
  {
    word: 'Mrs.',
    reason: 'Honorific abbreviation. Same issue as Mr. — always followed by a proper name.',
    recommendation: 'Skip.',
    status: 'avoid',
    notes: 'Was briefly added in an expansion pass; removed in audit.',
  },
  {
    word: 'Ms.',
    reason: 'Honorific abbreviation. Same issue as Mr. and Mrs.',
    recommendation: 'Skip.',
    status: 'avoid',
    notes: 'Was briefly added in an expansion pass; removed in audit.',
  },
  {
    word: 'Friday',
    reason: 'Proper noun (day of week). Content standards prohibit proper nouns as spelling targets.',
    recommendation: 'Skip. Days of the week are capitalized proper nouns.',
    status: 'avoid',
    notes: 'Was briefly added in an expansion pass; removed in audit.',
  },
  {
    word: 'Sunday',
    reason: 'Proper noun (day of week). Same issue as Friday.',
    recommendation: 'Skip.',
    status: 'avoid',
    notes: 'Was briefly added in an expansion pass; removed in audit.',
  },
  {
    word: 'America',
    reason: 'Proper noun (country name). Content standards prohibit proper nouns.',
    recommendation: 'Skip.',
    status: 'avoid',
    notes: 'Was briefly added in an expansion pass; removed in audit.',
  },
];
